### ISSUE TITLE
Define how to encode instrument transposition

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#111]
This issue notes the need to represent the transposition of instruments including both key changes and octave shifts.

This is related to the more specialized concerns in #4 and #34 but concerns the general nature of the transposition.

**Comment by clnoel** [comment]
I am commenting here to draw attention to the fact that there is an issue already to deal with these specifics, since part of the proposals in the general issue #138 include the addition of a `<transposition>` open-ended direction, which can handle several of the cases here. We should probably discuss here how to use that in conjunction with visible octava, key-changes, or clef-changes.

**Comment by adrianholovaty** [comment]
See pull request #158 for some work on octave shifts.

**Comment by adrianholovaty** [comment]
(Just renamed this issue to make the intent clearer.)

**Comment by adrianholovaty** [comment]
Marking this closed in favor of #287.
