### ISSUE TITLE
Multi-measure rests

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#121]
This issue notes the need for multi-measure rests in MNX-Common.

Within MusicXML this is covered under the `measure-style` element, which permits a single `measure` element to act as a multi-measure rest. We should look at how this fits into MNX-Common and whether this is still the best approach for producers and consumers.

**Comment by mdgood** [comment]
To clarify, in MusicXML the `multiple-rest` child element of the `measure-style` element permits a single `measure` element to encode both the start and length of a multi-measure rest. All the measures in the multi-measure rest still need to be represented by their own `measure` element. 

This doesn't change that we should look at the `measure-style` mechanism to see if there is a better way to fit this feature into MNX-Common.

**Comment by joeberkovitz** [comment]
Thanks for the clarification @mdgood. I could not remember how this feature worked.

**Comment by clnoel** [comment]
Multi-measure rests are a shorthand to save paper and help musician attention, not really directly semantic. The parts should either skip these measures entirely (with the understanding that a skipped measure is a full-measure-rest) or specify each measure as a full measure rest. Consumers who need to compress can compress multiple full-measure-rest measures however they please.

Just like with other printing decisions, I think it IS appropriate to specify this in the `<print-layout>` element that is still evolving (#57 ). Whatever method we decide for specifying system-breaks and other such things for different page widths would apply here as well for apply a multi-measure-rest style.

Alternatively, if we really want to specify this kind of thing in the part semantics, it should become a spanning direction, located at the first beat of the first compressed measure, with an ending location at the last beat of the last compressed measure. Specifying the number is optional, since counting the distance between the locations should be sufficient, but probably appreciated. Consumers that want to show all the measures ignore the direction; and consumers that want to compress apply whatever algorithm they use to hide barlines or give measures zero-width, or whatever.

**Comment by mdgood** [comment]
I believe that in a music notation format, a multi-measure rest is indeed semantic. It is representing musical symbols that appear on the page for a musician to read. Any such symbolic notations are semantic for the purposes of a notation format. It is representing musical meaning and is not a representation of layout.

**Comment by clnoel** [comment]
Oops, I didn't mean to say "semantic" as such, because you're right. Anything that has meaning is semantic. And the multi-measure-rest symbol definitely has a meaning that is understood easily by musicians.

But, when we're talking supporting reflowing applications and different page sizes, it becomes important to differentiate whether or not the symbol's purpose is to improve graphical understanding of the music in the particular layout that it was originally written in. There is no abstract musical difference between a four-measure multi measure rest and four measures with a whole-rest in them. They will both produce the same amount of silence. And, in fact, in an orchestra setting, a musician looking at only their own part might have a multi-measure rest while the conductor looking at that musician's part in their full score might have multiple measures with rests in them. It has the same underlying meaning, it's just a matter of the desired layout. If we represent it in MNX _as_ a layout decision, we can support the production of both versions with one `<part>` element.

**Comment by mdgood** [comment]
I don't think it's "just a matter of the desired layout," or even primarily about desired layout. There is a difference semantically between a 107-bar multi-measure rest and a series of smaller multi-measure rests that allow the musician to follow musical cues and tempo changes. Multi-measure rests done well encode musical form. When done poorly or not at all, they obscure it.

**Comment by clnoel** [comment]
We might have to agree to disagree about this one. To me, by its definition, a multi-measure rest is a shorthand for that many measure of rests. The fact that it improves (or hinders) readability puts it on the same level (to me) as three measures on a particular system vs. two measures. Stretching or compressing the distance between notes also improves (or hinders) readability without affecting the meaning behind the music.

But this debate is why I also suggested the spanning-direction option. What do you think about that one?

**Comment by joeberkovitz** [comment]
There are many things that I like about spanning directions for multirests. It's a simpler way to implement them that doesn't require a new MNX concept analogous to "measure style". Also, the multirest is a concrete, discrete notation that can have various tweaks done to it, not just a style applied to some other notated object.

However one could also take the view that multirests are a bit like system breaks. Done well, system breaks *also* encode musical form! And we are considering implementing system breaks as layout/style decisions that can vary according to whether one's viewing as a part or as a full score.

The fact that multirest groupings may be different for parts and the score is going to come up as part of a larger raft of topics including #34 (which applies more specifically to transposition). In many ways this is also analogous to the system/page break issue.

**Comment by notator** [comment]
According to [the current proposal for grouping parts](https://github.com/w3c/mnx/issues/185#issuecomment-643174127), a full score and its parts can be separately printable objects inside a single `<mnx-common>` element.
Here, for example, is a skeleton  `<mnx-common>` element with a single part (Violins II) given in detail:
(The `<systemLayout>` elements are as described in the original proposal, but (as @clnoel suggested) could contain `<staff>` elements in addition to `<staffGroup>` elements. I've used `<pages>` instead of `<scoreLayout>`)
```
<mnx-common>
    <!-- like the globals and parts defined in §6.1.7 in the current spec -->
    <globals>...</globals>
    <parts>... </parts>

    <!-- global systemLayout-definitions (optional) -->
    <systemLayouts>...</systemLayouts>

    <!-- all the scores in this mnx-common element -->
    <scores>

        <score name="Full Score">...</score>

        <score name="Flute 1 part">...</score>
        <score name="Flute 2 part">...</score>
        <!-- etc. more part scores -->

        <score name="Violins II part">
            <!-- optional, cascading globals for the Violins II part -->
            <globals>...</globals>
            <!-- systemLayout-definitions for the Violins II part -->
            <systemLayouts>
                <systemLayout id="violins2SysLayout1">...</systemLayout>
                <systemLayout id="violins2SysLayout2">...</systemLayout> <!-- divisi -->
                <!-- etc. more systemLayout elements -->
            </systemLayouts>

            <!-- pages (=scoreLayout) for the Violins II part-->
            <pages>
                <page>
                    <systems>
                            <system startMeasureNumber="1" systemLayoutID="violins2SysLayout1" />
                            <system startMeasureNumber="42" systemLayoutID="violins2SysLayout1" />
                            <system startMeasureNumber="50" systemLayoutID="violins2SysLayout1" />
                            <system startMeasureNumber="54" systemLayoutID="violins2SysLayout2" /> <!-- divisi -->
                            <system startMeasureNumber="60" systemLayoutID="violins2SysLayout1" />
                        <!-- etc. more systems -->
                    </systems>
                </page>
                </ etc. more pages -->
            </pages>
        </score>

        <score name="Violas part">...</score>
        <score name="Celli part">...</score>
        <score name="Double Basses part">...</score>
        <!-- etc., any other "scores" (booklets) -->
    </scores>
</mnx-common>
```
First thoughts:
Multi-measure rests definitely have to be possible in individual parts. Do full scores ever have multi-measure rests?
There are two alternative ways to approach this:
1. The information about the beginning and end of a multi-measure rest could go in a `<global><measure><direction>` (pair?). The information in `<global>` elements cascades, so could be put in a _part's_ `<global>` definition without affecting any other `<score>`s.
2. Multi-measure rests could be created _automatically_ where any `<score>` 's `<system>` contains a sequence of empty `<measure>` elements. (Both `<global><measure>` and `<part><measure>` elements would need to be empty for a multi-measure rest to be created).

As always, I lean towards the automatic solution if there are no objections. Its more work, always to have to define where multi-measure rests are created, but maybe the effort is worth it?

**Comment by notator** [comment]
Here's an example, showing how I'm proposing to code multi-measure rests. The top part of the following diagram is the "full-score", the other staves would be printed in the part-booklets:
<img width="348" alt="multiMeasureRest" src="https://user-images.githubusercontent.com/1655500/108362971-b0f90200-71f4-11eb-8499-a183eb4373bd.png">

The `<multiMeasureRest>` element is included in the system in the flute 2 `<score>` at the bottom of the following code. It could also have been enclosed in a `<partStaff>` or a `<partStaves>` (=piano part) element in that `<score>`.
Note that these are "degenerate" scores, each of which contains only one system. Scores can also contain multiple pages containing multiple systems containing multiple staves - see https://github.com/w3c/mnx/issues/185#issuecomment-780403076.
```
<?xml version="1.0"?>
<mnx
xmlns="https://github.com/notator/mnx"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://github.com/notator/mnx https://james-ingram-act-two.de/open-source/XMLSchemas/common1900.xsd">
    <global>
        <instrumentTypes>
            <instrumentType id="flute" groupName="Flutes" name="Flute" nameAbbrev="Fl." />
        </instrumentTypes>
        <measures>
            <measure>
                <directions>
                    <time signature="3/4"/>
                </directions>
            </measure>
            <measure/>
            <measure/>
            <measure/>
            <measure/> 
        </measures>
    </global>

    <parts>
        <part id="fl1" instrumentType="#flute" partNumberInGroup="1">
            <measures>
                <measure>
                    <sequence>                        
                        <event value="/2d">
                            <note pitch="C5"/>
                        </event>                        
                    </sequence>
                </measure>
                <measure>
                    <sequence>                        
                        <event value="/2d">
                            <note pitch="D5"/>
                        </event>                        
                    </sequence>
                </measure>
                <measure>
                    <sequence>                        
                        <event value="/2d">
                            <note pitch="E5"/>
                        </event>                        
                    </sequence>
                </measure>
                <measure>
                    <sequence>                        
                        <event value="/2d">
                            <note pitch="F5"/>
                        </event>                        
                    </sequence>
                </measure>
                <measure>
                    <sequence>                        
                        <event value="/2d">
                            <note pitch="G5"/>
                        </event>                        
                    </sequence>
                </measure>
            </measures>
        </part>
        <part id="fl2" instrumentType="#flute" partNumberInGroup="2">
            <measures>
                <measure>
                    <sequence>
                        <event value="/2d">
                            <note pitch="G4"/>
                        </event>
                    </sequence>
                </measure>
                <measure>
                    <sequence>
                        <event value="/4">
                            <rest/>
                        </event>
                    </sequence>
                </measure>
                <measure>
                    <sequence>
                        <event value="/4">
                            <rest/>
                        </event>
                    </sequence>
                </measure>
                <measure>
                    <sequence>
                        <event value="/4">
                            <rest/>
                        </event>
                    </sequence>
                </measure>
                <measure>
                    <sequence>
                        <event value="/2d">
                            <note pitch="G4"/>
                        </event>
                    </sequence>
                </measure>
            </measures>
        </part>
    </parts>
    
    <systemLayouts>
        <systemLayout id="fullScoreSystemLayout">
            <staffGroup name="Flutes" bracket="straight" barline="true" displayGroupName="true" >
                <partStaff part="#fl1" displayPartNumber="true" />
                <partStaff part="#fl2" displayPartNumber="true" />
            </staffGroup>
        </systemLayout>        
        
        <!-- systemLayout-definitions for the flute 1 part booklet -->
        <systemLayout id="flute1PartSystemLayout">
            <partStaff part="#fl1" displayName="true" displayPartNumber="true"/>
        </systemLayout>
        
        <!-- systemLayout-definitions for the flute 2 part booklet -->
        <systemLayout id="flute2PartSystemLayout">
            <partStaff part="#fl2" displayName="true" displayPartNumber="true"/>
        </systemLayout>        
    </systemLayouts>
      
    <scores>
        <score name="Full Score" relWidth="500" relHeight="220" relMargins="30">                        
            <system startMeasureNumber="1" systemLayout="#fullScoreSystemLayout"/>
        </score>

        <score name="Flute 1 part"  relWidth="500" relHeight="220" relMargins="30">
            <system startMeasureNumber="1" systemLayout="#flute1PartSystem1Layout"/>
        </score>

        <score name="Flute 2 part"  relWidth="500" relHeight="220" relMargins="30">
            <system startMeasureNumber="1" systemLayout="#flute2PartSystemLayout">
                <multiMeasureRest relWidth="205" startMeasureNumber="2" nMeasures="3"/>
            </system>
        </score>        
    </scores>
</mnx>
```

**Comment by notator** [comment]
The above posting leads me to suggest that we define some way to abbreviate a sequence of measure rests in a `<part>`. Imagine how the above file would look if Flute 2 had 50 or 100 measures rest. Perhaps we could do it like this:
```
    ...
    <part id="fl2" instrumentType="#flute" partNumberInGroup="2">
            <measures>
                <measure>
                    <sequence>
                        <event value="/2d">
                            <note pitch="G4"/>
                        </event>
                    </sequence>
                </measure>
                <restMeasures count="50" />
                <measure>
                    <sequence>
                        <event value="/2d">
                            <note pitch="G4"/>
                        </event>
                    </sequence>
                </measure>
            </measures>
        </part>
        ...
```

**Comment by notator** [comment]
In https://github.com/w3c/mnx/issues/185#issuecomment-971644199 I suggested the following, slightly different version:
```
     ...
    // Measures 6-16 contain rests in this example.
    <part id="ob1">...<part>.

    // Oboe 1 system-layout definition
    <system-layout id="Oboe1SystemLayout">
        // omitting the redundant <staff-layout> layer
        <part-layout part="ob1" label="Oboe 1"/>
    </system-layout>

    <score name="Oboe1PartBooklet" width="2200" height="373" margins="159 76 135 272" gap="20">
        // omitting the redundant, single <page> layer
        <system measure="1" layout="Oboe1SystemLayout" >
            <multi-measure-rest measure="6" label="2" ... />
            <multi-measure-rest measure="8" label="6" ... />
            <multi-measure-rest measure="14" label="3" ... />
        </system>
    </score>
```
![image](https://user-images.githubusercontent.com/1655500/142489786-ce9c709b-761e-4428-aea6-8fd8e97b19ce.png)

And @joeberkovitz replied:
> [...] I do not agree that we should have label and measure as the attributes, would rather see starting and ending measure indices. [...]

**Comment by adrianholovaty** [comment]
I've opened #284 with some concrete proposals on multi-bar rests, bringing this discussion up to date with our new layouts system. Closing this issue in order to keep things tidy, but I'll leave a comment on #284 with a pointer to this older thread.
