### ISSUE TITLE
Determine approach for separating content from presentation

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#146]
[Note that this issue is different from #11, which is specifically about styling text within a score.]

In MNX, we'd like to separate content from presentation when possible — but we haven't yet nailed down exactly how.

Joe B. had previously suggested using Cascading Style Sheets (CSS) for this. In my own view, that's an elegant solution in theory, but it would be cumbersome for developers in practice. It would mean MNX-Common parsers would need to parse/generate _two_ formats (XML and CSS). Though XML parsers are available for any commonly used programming language, CSS parsers are rarer. CSS also doesn't have much developer mindshare outside the world of web development.

It would be nice to achieve the broad benefits of CSS without requiring CSS syntax. Some specific features we should consider:

* Ability to set global styles (e.g., staff-line thickness/spacing, music glyph font)
* Ability to target specific pages (e.g., "use different margins on page 1")
* Ability to target types of notes/beats (e.g., "color every note of pitch C yellow")
* Ability to target specific notes/beats

Some large questions to ponder:

* To what extent is presentation stored in an MNX document? See [Joe's 2018 Musikmesse presentation](https://www.youtube.com/watch?v=_Ot_ggpkdag) (the section starting at 1:14:27) for a spectrum of intriguing options.
* Should styles be contained in a single place within the document, or would we support inline styles?
* What's the full list of styles we should support?

**Comment by bhamblok** [comment]
I strongly believe in CSS. It is a well established language, and it has proven itself to a great extent to be an ideal solution for separating content from presentation.
Though, even within the web development-world, there are a lot of developers not being comfortable with some basics of the language. There are endless discussions in the web development world to use CSS-in-JS (which I personally do not agree upon) to solve "their problem" of global-scoping vs local-scoping of CSS-properties on their modular-development-patterns. These discussions prove that some basics of CSS are not known well enough and that the language has its difficulties in using it in correct way.

That being said, I really think we should go for CSS in MNX, because it's so powerful! :-)
It does not only separate content from presentation in a beautiful way, but it can also be applied on another technical level, deeper on "the metal". Well written CSS (in the web development world) improves performance of the rendering of the content, because most of the processing is done by the GPU, not the CPU!

So, if we would agree on using CSS in MNX, here is another question to ponder:
Should MNX support all styles (properties and values) of CSS as we know CSS in the web development world? In other words:
- is CSS in MNX a superset of CSS in Web?
- is CSS in MNX a subset of CSS in Web?
- or is CSS in MNX a similar approach of separating content from presentation as in Web, but has furthermore nothing in common with CSS in Web?

I feel like the first option: CSS in MNX should be a superset of CSS in Web where all properties and values of CSS in Web could be used/implemented as well on MNX-elements where appropriate.

**Comment by dhoernel** [comment]
The current MNX draft specification is built on the achievements that have been reached with MusicXML. But it also introduces some new design principles which are very well summarized here:
https://w3c.github.io/mnx/specification/#design-notes

One is about "Separation of semantic concerns from presentation/interpretation concerns". I think it is important to follow it in order to get the robustness we are trying to achieve.

CSS has the advantage to be a well-established standard. It could be used to create a uniform look, e.g. for coloring all notes in a specified voice, but style could also be attributed to single elements, e.g. for horizontally shifting a note with default-x.

One aspect: At present when importing a MusicXML score which has not been created by your own program, you will probably read in most semantic elements and attributes which are essential to correctly display the score. But you will also ignore or partially ignore some presentation attributes like default-x or interpretation attributes because your layout engine differs from the layout engine of the program that wrote the MusicXML, or because you are interested in displaying the score, but not in playing it (or vice versa). This means that you have to know exactly what attributes are semantic or presentation/interpretation attributes. What I would find appealing is that I do not have to know that when importing a score, but I can simple consider/ignore the "levels" (semantics/presentation/interpretation) which I am interested in or not. For example, when I do not want to colorize notes, I simply ignore the corresponding styling directive, otherwise I am looking for the elements addressed by the styling and apply it to them.

**Comment by cecilios** [comment]
The use of CSS was considered and finally discarded. See #83. Why are we now reopening the issue of using CSS? Having to use a general CSS parser and selector-engine for supporting MNX will add a lot of complexity. The solution agreed in #83 is much simpler and fullfils the requirements. Therefore, I would suggest to identify use cases for which the agreed solution will not work, instead of opening a general discusion about the benefits and drawbacks of CSS.

**Comment by adrianholovaty** [comment]
Whoops, this is my mistake. Thanks, @cecilios, for pointing that out! Marking as duplicate of #83.
