### ISSUE TITLE
Specify how/whether barlines are encoded

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#165]
The MNX-Common spec should explicitly state whether barlines must be encoded. A couple of options:

* Treat them as opt-out: i.e., the document assumes barlines exist and are rendered, without needing to explicitly specify them, unless you turn them off.
* Treat them as opt-in: i.e., the document assumes barlines are _not_ rendered unless you explicitly specify them.

My inclination is to treat them as opt-out, given that the vast majority of CWMN will use barlines in the common way. This will make MNX-Common encodings simpler and will cause fewer mistakes (e.g., people forgetting to encode the barlines).

Note there are a few types of barlines I think this "opt-out" should apply to:

* Regular barlines (e.g., in the middle of a system)
* Systemic barlines (e.g., at the start of a system, connecting staves)
* Final barline (e.g., at the end of the piece)

For out-of-the-ordinary barlines, such as double barlines, it seems clear that those should be opt-in.

**Comment by cecilios** [comment]
Perhaps this issue is related to #61. And also to the very old issue of the role of the `<measure>` container: whether it represents a measure or it is just a helper container (equivalent to a html div).

It is not my intention to re-open old issues, but just to recall that it was decided that `<measure>` will be a _rich_ container representing a measure, as in MusicXML, and not just an auxiliary helper container. Therefore, if `<measure>` represents a measure, the most logical conclusion is to accept that a barline is by default implied at the end of the measure. Thus, the opt-out seems to be the only coherent option for regular barlines.

As to final barlines, probably it is better to use a fixed default (regular barline) instead of a default that changes depending on the position of the measure element (regular or final barline). Both options are acceptable to me. But if final barline is implied by last measure container, then for use cases such as snippet scores there should be a way of overriding this and placing, instead, a regular barline.

As to the systemic barline, I'm not sure if it is implied by the measure container or by the fact of laying out a score with metric. I think of it more as a global option for score layout or a local direction, that something implied by a measure container, but that's just my feeling and I can not give supporting arguments.

**Comment by clnoel** [comment]
System barlines should be part of the layout style, however we end up specifying that, not part of the measure container. Different layouts will have the system barlines in between different measures, or might only be extracting one part, or might be a snippet that doesn't need a system barline at all.

**Comment by adrianholovaty** [comment]
Pull request #171 addresses this.

**Comment by adrianholovaty** [comment]
This was addressed by commit 1f6b11c.
