### ISSUE TITLE
Change slurs to be liaison content

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#167]
At the moment, the MNX-Common spec treats slurs as [spanning directions](https://w3c.github.io/mnx/specification/common/#common-spanning-directions), which led to the pull request #159 implementation. But we've come to realize slurs would be treated better as [liaison content](https://w3c.github.io/mnx/specification/common/#common-liaison-content).

See [this comment](https://github.com/w3c/mnx/pull/159#discussion_r328227208) from @mdgood for more context.

The difference is:

* Spanning directions are defined from one metrical position to another. For example: "This slur spans from a quarter note into bar 2 until three quarter notes into bar 2."
* Liaison content is defined from one _specific_ note/event to another.

Any objections or further thoughts regarding making slurs be liaison content?

**Comment by clnoel** [comment]
The thing about slurs is they are not only on specified start and end notes, they also affect only particular notes in between. For example if you have the slur on a set of down-stem notes, the up stem notes (or notes in the other staff) are not necessarily affected. Does liaison content cover that?

**Comment by adrianholovaty** [comment]
@clnoel I believe that wouldn't be a problem. In your example, the up-stem notes would live in a different voice (a different `<sequence>` in MNX-Common terminology). Liaison content goes from one specific note (which lives in a specific `<sequence>`) to another specific note (which lives in a specific `<sequence>`). Same goes for notes in the other staff. Counter-examples are welcome, of course!

**Comment by clnoel** [comment]
The only counter I can come up with is a slur that spans several measures. The notes in the first and last measures that belong in the slur would be well defined by sequence and liaison specification, but not the notes in the middle measures. If we do this, we need to make a way to optionally specify one or more "midpoints" not just an end point. 

That might be a general requirement for liaison content. Arpeggios could be very well defined this way, and so could slides and bends. Multi-note ties could also benefit from this, so that it is considered a single element instead of a tie that ends on one of the middle notes and then restarts to go on to the next one. (That reflects how its played, and is good for figuring actual note duration fro playback, and display can still stop at each midpoint note.)

**Comment by adrianholovaty** [comment]
Pull request #169 addresses this issue.

**Comment by clnoel** [comment]
While I have no objection to improving the slur specification as written here, I would like to call out that my issue is not addressed by this. I've pulled the following example from the dorico website http://www.rpmseattle.com/of_note/how-to-work-with-slurs-in-dorico-write-mode/

![dorico-cross-staff-slurs](https://user-images.githubusercontent.com/6453511/68787583-6ce97b80-0607-11ea-9a82-3f4807892fc0.png)

In this picture, One side of the slur is in the lower staff, the middle of the slur is in the upper staff on downstem notes (and there are upstem notes that are a separate sequence), and the end of the slur is an upper staff chord that has no opposing sequence. It would be extremely hard for a program to figure out that the middle system's sequence is part of this slur, given the current liaison structure that allows just a start and end point. Both audio generation and the graphical generation of creating a nicely shaped curve would be complicated. And would be even more complicated if there were more notes in the lower staff here.

**Comment by adrianholovaty** [comment]
This is now done, as of commit e273246.
