### ISSUE TITLE
Rename barline types to have friendlier names

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#172]
As suggested by @mscuthbert in https://github.com/w3c/mnx/pull/171#issuecomment-553106161, I think we should change the allowed barline type strings to be a bit more human readable. Specifically, these changes would be good:

* `light-light` becomes `double`
* `light-heavy` becomes `final`

Lest somebody think this is bikeshedding, I do believe there's a good reason to change the names for these two in particular. They're just easier to understand! And we have some inadvertent evidence: Joe Berkowitz used `barline="final"` in some of the original MNX-Common examples (which I've made consistent in #171). :-)

The downside of this change is that it's inconsistent with MusicXML, but I believe the increase in usability is worth it (and it's a clear/obvious migration for people making MusicXML-to-MNX-Common converters).

As a reminder, here is the current list of barline types, [per the spec](https://w3c.github.io/mnx/specification/common/#element-attrdef-measure-barline):

* `regular`
* `dotted`
* `dashed`
* `heavy`
* `light-light`
* `light-heavy`
* `heavy-light`
* `heavy-heavy`
* `tick`
* `short`
* `none`

**Comment by mscuthbert** [comment]
Great!  This is already what we use in `music21` for names:

```
# former are MusicXML names we allow as synonyms.
barTypeDict = {
    'light-light': 'double',
    'light-heavy': 'final'
}
```

**Comment by clnoel** [comment]
As long as we don't remove "light-heavy" as an option, but rather use "final" as a synonym for it, I'm okay with this. After all, there are other occasions than the end of a piece where a light-heavy barline is used. Repeats, of course, being the most common.

I note, however, that Repeats have not been defined yet, so maybe the special barlines needed for repeats should be defined inside the repeat element instead of in the measure.

**Comment by shoogle** [comment]
I support this. Using `double` and `final` is more semantic than `light-light` and `light-heavy`. It's similar to how `<i>` (italics) in HTML was replaced with `<em>` (emphasis), which is more meaningful to non-sighted users.

**Comment by samuelbradshaw** [comment]
Technically, there are still cases where <i> is useful in HTML5. <em> would be used for emphasizing something in a paragraph, because that's what it means semantically, but not all italics are about emphasis. For example, in this case, it's not emphasis at all, it's just about an italic style – so <i> would still be used:

_Author:_ John Smith
_Composer:_ Sally Jones

Similarly, are there cases where these bars would be used that don't semantically fit with the wording "double" or "final"? If so, having synonyms would make sense.

**Comment by adrianholovaty** [comment]
Would there ever be a case of music where a `light-light` barline label would be appropriate while `double` wouldn't (or vice versa)? I can't think of one...

A stronger case can be made for the semantic difference between `light-heavy` and `final` (thanks for the points, @clnoel and @samuelbradshaw). But keep in mind this is merely the name of a barline style, as opposed to a description of the function of the music.

**Comment by shoogle** [comment]
> there are other occasions than the end of a piece where a light-heavy barline is used. Repeats, of course, being the most common.

Are there any examples other than repeats? Maybe at the end of a movement, but that is still "final" in the sense it is the final barline in that movement. (You could say the same about the final barline in a repeat.)

Regarding repeats, the [draft spec says](https://w3c.github.io/mnx/specification/common/#the-repeat-element) that the repeat element (which is unfinished) is separate to barlines. Why is this? Why not drop the repeat element and just use special `start-repeat` and `end-repeat` barline types?

**Comment by mdgood** [comment]
I find that synonyms for type values add complexity to software, and music notation formats are complex enough as is. So I recommend we choose one set of names or the other, not include synonyms for both. As this proposal is for MNX, not MusicXML, automated conversion in both directions would be easy to implement. A change would not seem to complicate application software.

We may also want to consider an MNX approach to the issue of back-to-back repeat barlines, brought up originally as a MusicXML issue at https://github.com/w3c/musicxml/issues/104. I suspect we would want to deal with this at the presentation level rather than here at the semantic level. So while it probably doesn't interact, this proposal might lose the parallel between light-heavy and heavy-light for repeated sections. That might well be worth it for names that are generally more clear and concise.

**Comment by shoogle** [comment]
I agree that we should choose one set of names or the other. My vote would be for `double` and `final` rather than `light-light` and `light-heavy`, but either option is preferable to allowing both.

However, I disagree that repeats should be non-semantic. I would prefer to make `start-repeat` and `end-repeat` proper barlines in their own right. This would make the format much easier to read than if there is a separate element for repeats.

If anything is to be considered "non-semantic", it should be the physical appearance of the barline. I can envision something like this:

```xml
<barline type="start-repeat" lines="thin,thin" dots="4"/>
```

Here, the type is semantic information that affects score playback, and also provides a default appearance if `lines` and `dots` are not specified. The defaults for `start-repeat` would be `lines="thin,thick"`, `dots="2"`, but in this case they have been overridden with other values.

**Comment by adrianholovaty** [comment]
I've made the change in 6cf160229.
