### ISSUE TITLE
Repeats and alternate endings

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#174]
The MNX-Common spec [hasn't yet implemented repeats](https://w3c.github.io/mnx/specification/common/#the-repeat-element) or [alternate endings](https://w3c.github.io/mnx/specification/common/#the-ending-element). Here's a dump of examples and questions to ponder.

First, some notes/observations:

* We need to encode the "start repeat" and "end repeat" locations, which might be in separate bars.
* Semantically, "start repeat" means "the bar that's returned-to after the end-repeat bar is performed." "End repeat" means "the last bar that's performed before jumping to the start-repeat bar."
* "Start repeat" might be missing/implied (see Example 2 below).
* We need to encode the number of times to repeat (see Example 3 below).
* In cases with more than two alternate endings, engraving practices differ (see Examples 5 and 6 below).
* A single bar might contain more than one ending number (see Example 7 below).

Some examples, so we have concrete things to consider:

**Example 1: Simple repeat**

<img width="496" alt="Screen Shot 2020-03-31 at 11 43 43 AM" src="https://user-images.githubusercontent.com/180401/78012174-e4b10c00-7344-11ea-8eaf-86b238d7eb2f.png">

**Example 2: Simple repeat with implied start-repeat**

<img width="497" alt="Screen Shot 2020-03-31 at 11 49 46 AM" src="https://user-images.githubusercontent.com/180401/78013226-7a00d000-7346-11ea-9c80-88008c54dad1.png">

**Example 3: Simple repeat with 4x**

<img width="499" alt="Screen Shot 2020-03-31 at 11 50 02 AM" src="https://user-images.githubusercontent.com/180401/78013245-7f5e1a80-7346-11ea-8cc1-14cdab0e5886.png">

**Example 4: Simple alternate endings**

<img width="588" alt="Screen Shot 2020-03-31 at 11 51 30 AM" src="https://user-images.githubusercontent.com/180401/78013295-8f75fa00-7346-11ea-9b29-1097d3f23bd0.png">

**Example 5: Three alternate endings (two end-repeat bars)**

<img width="722" alt="Screen Shot 2020-03-31 at 11 52 09 AM" src="https://user-images.githubusercontent.com/180401/78013321-98ff6200-7346-11ea-8516-91c021bae420.png">

**Example 6: Three alternate endings (one end-repeat bar)**

This is an alternate approach to Example 5. Only one end-repeat bar is visible.

<img width="724" alt="Screen Shot 2020-03-31 at 11 52 27 AM" src="https://user-images.githubusercontent.com/180401/78013364-aa486e80-7346-11ea-9707-9b06046400d0.png">

**Example 7: Three alternate endings, with one bar containing two ending numbers**

<img width="729" alt="Screen Shot 2020-03-31 at 12 00 19 PM" src="https://user-images.githubusercontent.com/180401/78013795-4c685680-7347-11ea-9ebb-6484be13fb85.png">

**Example 8: Repeat with an ambiguous start**

Here, it's not clear whether bar 3's repeat should jump to bar 1 (the start of the piece), jump to bar 2, or be considered invalid.

<img width="604" alt="Screen Shot 2020-03-31 at 12 14 23 PM" src="https://user-images.githubusercontent.com/180401/78015232-6dca4200-7349-11ea-81d8-9da51dd036ff.png">

**Questions**

1. How does the [measure element's](https://w3c.github.io/mnx/specification/common/#the-repeat-element) "barline" attribute fit in? Is that semantic enough, or would we consider that presentational?
2. In Example 2, does the implied start repeat need to be encoded? Encoding it would make playback easier, but it's not strictly necessary information.
3. Example 3 suggests there needs to be a way to encode the number of times to repeat. Is this required or should we have a default?
4. When encoding the number of times to repeat, do we encode the number of times _repeated_ or the number of times _performed_? In Example 3, number of times performed is 4 and number of times jumped is 3. This is a subtle distinction that has tripped up some of the customers of my own notation software, FWIW.
5. How do we reconcile the different approaches to engraving multiple alternate endings demonstrated in Examples 5 and 6?
6. How do we handle the ambiguity of Example 8?

Opinions and proposals welcome! And if you have other examples and questions, please bring those up as well.

**Comment by bhamblok** [comment]
In the point of view of only encode "that" what needs to be visualised, it makes answering some of these questions a lot easier (except the first one :-) )

Let's start with answer 2...

2. My opinion is not to encode things which are implied.
3. We should have a default. A simple repeat barline implies only one repeat. Of course we need to specify some place (an element or an attribute) to be able to define the number of times to repeat when necessary.
4. Being a fan of encoding what is being visualised, this question is being answered: "The number of times performed".
5. I would encode "repeat-ending"-elements and "repeat-barlines" which can be referencing to one and each other by means of an id.
6. This is ambiguous for the musician as well. So choices have to be made by the consumer of this "file", being it the developer of the software using this file, or the musician who has to perform the music while reading this. In my opinion, a mistake (or an incompleteness) has been made by the composer/engraver (unintentional or not)... So I would not encode anything here which is not being visualised either.

If/when we specify the needed elements (repeat-ending, repeat-barline, repeat-times), developers/composers/engravers can use them as they need. It's up to "us developers" to create software that makes things unambiguous. Unfortunately we can not restrict every usecase (eg. the differences in example 5, 6 and 7) within the mnx-file-format without being able to support every visualisation which has been created in sheet music history (aka CWMN).

That brings me to answering question one:
1. I would specify everything about "repeats" in their representative elements, not in a "barline"-attribute. So I would remove the options of having the value "repeat-start", "repeat-end", ... in a barline-attribute. So am I right to consider the barline-attribute only as being presentational?

**Comment by notator** [comment]
Here are my intuitions about the original questions:
1. I don't know how barlines should relate to MusicXML's `<measure>`-attribute, but see my answer to question 6 : Maybe barlines should be elements, not attributes.
2. If all `repeat-end` barlines send the performer back to measure 1 by default, then the answer is "no":  In Example 2, the implied `repeat-start` does not need to be encoded. Apropos: like @bhamblok , I think the point to which a performance is sent by the `repeat-end` barline should be managed using an id. Maybe I'm wrong but, as I remember, that point does not necessarily have to be at the start of a measure... (Has anyone got an example for that?) How does MusicXML stipulate a `repeat-start` barline in the middle of a bar?
3. In Example 3, the default should be one repeat (i.e. play everything twice).
4. Example 3 again: The number (in the XML) should be the number of times performed. The value of this number must be greater than 1. (Some weird client might decide to write something else in the score, but the number of times to play the same music must be unambiguous.)
5. Examples 5 and 6 could be coded identically, except that in Ex. 6 there could be an additional, attribute (that can be ignored by the client) saying that the barline at the end of measure 2 should ideally look like a `regular` one (i.e. `barline="repeat-end" barline-appearance="regular"`).
6. Examples 5, 6, 7 and 8 are unambiguous if all `repeat-end` barlines send the performer back to measure 1 by default. If, in Example 8, it was intended that measure 3's repeat should jump to the beginning of measure 2, then measure 1's barline would have to be a `repeat-end-start`. I'm wondering if barlines should be elements rather than attributes, so that they can have an id to which to jump. Alternatively, the jump could of course be to the first event symbol after the barline, and measure 1's barline would be a `barline='repeat-end' barline-appearance='repeat-end-start'`.

**Comment by clnoel** [comment]
1. I agree that we should separate the concept of a "jump", a  non-linear progression through the music, from the notations that cause it. From this perspective, I would like to keep the "presentational" aspects of a :|| barline (however it is represented) to be separate from the "repeat-end" semantic information. This would allow us to use this same kind of information in "D.C." or "D.S." or "To Coda" instructions when our spec progresses to them.

As such I would like to propose that we use a paired attribute: jump-id, jump-to. It can attach to directions in general, or to barlines, and when you hit a jump-to (on a repeat end), you go to the jump-id that matches (on a repeat start, or the start of a piece). I think I've proposed something similar in a different thread/issue but I can't find it now.

Doing this properly will allow presentation methods that need to unroll the music (not just audio, but also a forward-only page turn kind of visual) to know where to go for the next measure.

2. I'm on the fence about requiring a "jump-to" specification. My intuition is that such references should be optional playback hints like several other performance specifiers. If someone encoding the file doesn't want to include it, then its up to the recipient to interpret the graphics according to their own algorithm.

3&4.  Each time you hit the same "jump-to", you might end up going somewhere else, which needs to be represented. So in Example 3 you could put jump-id="start" on the beginning of the piece, and then at the repeat bar specify jump-to="start;start;start;;" to indicate jumping to the start three times before moving on. The final "blank" specifier indicates moving on to the next measure, and is optional. If you hit the jump-to specifier more times than are specified, you automatically move to the next measure.

5. Since we are not tying the "jump-to" to particular elements (like a repeat bar), there is no problem here. Assuming we have all the other graphical elements in place, which would need to be handled separately anyway due to style differences (ending-begin-closed, ending-begin-open, ending-end-open, ending-end-closed, for example), the jump-to on each barline in either case ends up being (1) ";second;third" (2) "" (3) "start;start" (4) "" It doesn't matter what they look like for the playback hints. It's whether the _next visual measure_ is the one that gets played. Alternatively, we could actually attached the jump-to commands to the ending brackets instead!

6. If "jump-to" is not required (which I'm guessing it won't be), then we don't _have_ to deal with that ambiguity at all. A person creating the mnx file can _choose_ to hint one way or the other by picking a particular "jump-to" sequence, or leave it up to the receiving algorithm. (Just like it's up to the performer to pick what it means in a print copy.)

I would also like to point out that this makes these files essentially have the basic programming concept of a "goto" command! I feel like this system will be very intuitive for the programmers creating the mnx files to pick up on and use!

**Comment by adrianholovaty** [comment]
I've added pull request #186 with a suggested encoding for repeats and jumps. Feedback welcome! (Please leave it on the pull request, so that the feedback is right at the source.)

**Comment by adrianholovaty** [comment]
Marking this as closed, as we've worked out the design for repeats and jumps (see docs: [jumps](https://w3c.github.io/mnx/docs/concepts/jumps/), [repeats](https://w3c.github.io/mnx/docs/concepts/repeats/)).
