### ISSUE TITLE
§6.4.1 The note element (accidentals)

### ISSUE THREAD

**Issue by notator** [w3c/mnx#184]
For MNX purposes, the issues raised in #180 (which came from the MusicXML repo) and https://github.com/w3c/mnx/issues/176#issue-614831933 need to be addressed in the context of [§6.4.1 of the Draft Spec](https://w3c.github.io/mnx/specification/common/#elementdef-note).

For purposes of this discussion, I'll assume that the Chromatic Pitch Syntax used in the note's `pitch` attribute is as I described in https://github.com/w3c/mnx/issues/176#issue-614831933:
```
(1 character in range [A..G]) +
(one of the strings in { "", "#", "##", "b", "bb"} ) +
(one of the strings in { "", "q#", "qb"} ) +
(1 character in range [0..9])
```
This describes both a (default, equal-temperament) frequency and a (context dependent) graphic.

I also proposed in https://github.com/w3c/mnx/issues/176#issue-614831933 that the values of the `accidental` attribute should be restricted to "visible" and "hidden". (A value of "hidden" means, as in CSS, that the accidental glyph does not exist at all, and therefore takes up no space on the page.)
@mdgood (in https://github.com/w3c/mnx/issues/180#issuecomment-627511829) agrees that the `accidental` attribute "could likely be improved", and suggests that a value of "auto" could be made the default. I'm not convinced that we need "auto", but am prepared to be convinced otherwise. :-)
Can anyone provide a use case that requires the use of "auto"? (I think its sufficient for "hidden" to be the default.)

Apropos the discussion in #180 about custom accidentals and specialised tunings. I'd like to think about including the following optional `note` attributes: `accidentalGlyph` and `cents`. These would override the graphical and temporal default values described by the Chromatic Pitch Syntax in the `pitch` attribute. The glyph attribute would take a SMuFL code point as its value. The `cents` attribute would describe the frequency in terms of a deviation from default equal-temperament tuning of the base pitch in the `pitch` value (i.e. ignoring any accidental in the `pitch` value) . (The note's intended frequency could be described in other ways, but we can look at that later.)
For example (see http://sagittal.org/Sagittal-SMuFL-Map.pdf):
```
<note pitch="Gqb4" accidentalGlyph="U+E303" cents="-21.506"/>
```
Here, the `accidentalGlyph` overrides the quarter-flat (`qb`) in the `pitch` attribute. The `cents` attribute describes a deviation from the (equal temperament) frequency of G4. An application that cannot display `U+E303` would fall back on the quarter-flat, and an application that can display neither accidental would, in this case, fall back on a natural (displaying it, or not, as it thinks fit).
Regardless of whether they can display the desired accidental, applications might still be able to play the correct pitch. All the information is there for the having.
There are obviously other ways to define such attributes. What would be best for _all_ tuning systems?

Notes:
1. A specialized glyph for the notehead could override the default glyph in a similar way:
```
<note pitch="Gqb4" accidentalGlyph="U+E303" headGlyph="U+E0BB" cents="-21.506"/>
```
2. Towards the end of §6.4.1 it says that further note attributes need to be imported from the MusicXML...

**Comment by cmloegcmluin** [comment]
@notator I'm sorry I took so long to get my thoughts on this issue to you. 

I think the way you've proposed this so far seems powerful. I like the ability to fall back to the pitch field. 

But there's one major issue that this proposal does not address: _multiple accidentals_.

Many popular microtonal notations, including Sagittal's [Prime Factor notation](http://forum.sagittal.org/viewtopic.php?f=4&t=99), [Extended Helmholtz-Ellis Just Intonation Prime Notation (EHEJIPN)](https://marsbat.space/pdfs/notation.pdf), and [Ben Johnston's notation](https://www.kylegann.com/BJNotation.html) all call for potentially multiple accidentals per notehead. If digital notation fails to support multiple accidentals, then microtonalists are forced to work around their software, hacking together solutions to fake the combination of visual and audio alteration, which are often tedious to implement and maintain.

If there were any way to extract an \<accidental\> from \<note\> as its own element which could have a one-to-many relationship with \<note\>, that would be preferable. And if the total pitch of the note could be the sum of all the individual alterations (in cents should be acceptable). 

I see one bit of evidence for an accidental element being a thing here: https://github.com/w3c/mnx/blob/801a29a20001037363d7b7978938346f63b3545f/examples/FaurReveSample-MusicXML.xml

Let me know if you have any questions or concerns about this.

**Comment by notator** [comment]
Thanks for getting back here! :-) And thanks for the links. Sagittal Prime Factor notation was especially relevant.

The good news follows at the bottom of this posting, but first here's a little background, just to be sure we're on the same page:

This CG has decided first to develop an MNX format that describes "basic CWMN", and then to develop a new format (formats?) containing more advanced features on top of that. For me, "basic CWMN" is CWMN as it was around 1900: i.e. the notation used by the late Romantics. I think there are a large number of potential users for such a format, and that they should not be forced to implement all the features contained in the more advanced format(s).
The CG (co-chair) still has to decide exactly what goes into the basic MNX format. The nearest I can find to a definition is the [V1 Milestone](https://github.com/w3c/mnx/milestone/2), but all the Milestones seem a bit out of date...

If I'm right in identifying basic MNX with CWMN 1900, then it should not contain things like fanned beams or temporal information. (Scores in 1900 were written on paper, so contained no temporal information. In 1900, temporal information was all in the performers' minds, in the form of learned _performance practice_. The whole point of _writing_ (especially on paper) is that it is _timeless_ (can be printed identically at different times).

---
So, to your request for _multiple accidentals_:
I currently think that both microtone accidental glyphs and the frequencies they represent belong in an "advanced" format -- but I could be wrong there. (As I said, the exact scope of basic MNX has yet to be decided.)
Given that microtone accidentals are going to be implemented _somewhere_, the inclusion of a multi-accidental capability depends on
1. how much demand there is for them in the community
2. how much extra code would be needed for their implementation.
(Everyone claiming to support the format has to include such code.)

Not every new-fangled suggestion makes it into a standard...
Here's the good news: The extra code would be minimal. In the above example:
```
<note pitch="Gqb4" accidentalGlyph="U+E303" cents="-21.506"/>
```
The value of the `accidentalGlyph` attribute could simply be a ':' separated string.
```
<note ... accidentalGlyph="U+E303:U+E305" ... />
```
That would be consistent with other ':' separated strings in MNX. For example: [§5.5 Measure location syntax](https://w3c.github.io/mnx/specification/common/#measure-locations)

In this case, a `cents` attribute would still override the notation, so the multiple accidental would make no difference to an application that consumes the temporal info. (Perhaps it would be better after all if the `cents` attribute were replaced by a simple `frequency` attribute?)
On the other hand, if the `accidentalGlyph` string were to be included in a file containing no temporal info (i.e. no cents or frequency attribute), the frequency could be inferred from the accidentals by specialised software without imposing that burden on software that does _not_ support temporal info. Maybe that means that microtone notation (i.e. the use of Unicode glyphs) is simple enough to include in basic MNX (that has no temporal info) after all. Hope that makes sense! :-)

I see that some Sagittal accidentals are associated with[ _three Unicode points_](http://forum.sagittal.org/viewtopic.php?f=4&t=99). Is that relevant here?

**Comment by cmloegcmluin** [comment]
Thank you so much for the helpful background information. 

I can see the argument, certainly, for microtonal notations being "advanced", or not CWMN circa 1900. Though I am obligated to insist that microtonality is not new, and that the 12-TET standard has only existed for barely 100 years (if you haven't read it yet, [Kyle Gann's The Arithmetic of Listening: Tuning Theory & History for the Impractical Musician](https://www.press.uillinois.edu/books/catalog/42gwm4em9780252042584.html) has an excellent overview of how technological improvements to the piano in the early 20th century made such standardization possible). This dovetails with your organizational principle of separating spatial and temporal information.

> I see that some Sagittal accidentals are associated with[ _three Unicode points_](http://forum.sagittal.org/viewtopic.php?f=4&t=99). Is that relevant here?

You've caught a bug in that table; we failed to fully update it earlier this year. Thanks!

While that particular table entry was wrong — it should have been only two Unicode points — you have reminded me of something I should have already said. In my previous comment on this thread I listed Sagittal's Prime Factor notation as an example of a notation which calls for multiple accidentals on a single note. You may have inferred that other Sagittal notations do _not_ call for multiple accidentals per note, and in fact, a secondary intention of mine was to imply that to be the case. But I neglected to consider that while indeed _in some sense_ all other Sagittal notations only use one accidental per note, digital music notation software won't think of it that way. Some Sagittal symbols, such as the one you referred to in your link, are what we call "accented"; they have the quintessential arrow-shaped ("Sagittal" comes from Sagittarius, the ancient Greek god of archery) main symbol, but also a smaller mark just to the left of it, indicating a very slight pitch alteration, no more than a couple cents. So in Sagittal's domain we consider such a combination of an accent + core to be a single symbol or accidental, in the domain of digital music notation software — because they are two different glyphs (or Unicode codepoints), and glyphs are roughly synonymous with accidentals in this domain — this is tantamount to having two accidentals. This is all to say that the issue of multiple accidental support is of even more importance to the Sagittal notation system than I originally was thinking. 

> In this case, a cents attribute would still override the notation, so the multiple accidental would make no difference to an application that consumes the temporal info. (Perhaps it would be better after all if the cents attribute were replaced by a simple frequency attribute?)

I'm sorry, but I don't follow your comments here. Could you explain why using frequency rather than cents would make a difference as to whether or not an application with temporal support could effectively handle multiple accidentals' cumulative pitch alterations? Or have I misunderstood your intention?

> On the other hand, if the accidentalGlyph string were to be included in a file containing no temporal info (i.e. no cents or frequency attribute), the frequency could be inferred from the accidentals by specialised software without imposing that burden on software that does not support temporal info. Maybe that means that microtone notation (i.e. the use of Unicode glyphs) is simple enough to include in basic MNX (that has no temporal info) after all. Hope that makes sense! :-)

It certainly makes at least some sense (or does it make "no cents"? 😆 ), and is encouraging. Perhaps I can whittle this down to just exactly how it would in my dreams. So in my music notation software of choice, I can drag a conventional sharp symbol from a panel of accidentals onto a note head and — voilà — the application has registered it as a proper accidental, insofar as it knows the rules for canceling it at the next bar line, it knows to adjust the pitches of notes at that staff position within the bar, etc. But for my scores notated with Sagittal symbols, I have to fake everything. I can drag in the visual symbol, but as far as positioning it and altering pitches of notes, it's all manual, under the hood stuff. It'd be a sea change if I could just even get first-class support for microtonal accidentals with a single accidental per note, since that will handle maybe 90% of use cases. But if I could pile on two or three (...sometimes four or more, though that's starting to get fairly insane) accidentals and have them all automatically affect the pitch and follow cancelation rules, etc. that'd be the ultimate win here.

**Comment by notator** [comment]
I said:
>> In this case, a `cents` attribute would still override the notation, so the multiple accidental would make no difference to an application that consumes the temporal info. (Perhaps it would be better after all if the cents attribute were replaced by a simple frequency attribute?)

@cmloegcmluin asks:
> Could you explain why using frequency rather than cents would make a difference as to whether or not an application with temporal support could effectively handle multiple accidentals' cumulative pitch alterations? Or have I misunderstood your intention?

The misunderstanding is rather subtle... The best way to explain things is to back up a bit.
Its all about overriding attributes:
A simple note element without Unicode accidentals might look like this:
```
<note pitch="Gqb4" />
```
That's a G4 with a quarter-flat accidental. The application decides _which_ quarter-flat accidental to use.
If the application supports playback of the score, it can infer pitches that belong to an equal temperament, quarter-tone scale.

A note that wants to use _particular_ accidental glyphs would use (one or two) Unicode glyphs like this: 
```
<note pitch="Gqb4" accidentalGlyph="U+E30F:U+E30E" />
```
If the application does not support the use of Unicode glyphs, it falls back on the "Gqb4" accidental and prints that.
If the application supports playback of the score, it could infer frequencies using the basic (standard equal temperament) G4 and an alteration due to the Sagittal accidental(s).
According to the following table (taken from the above Sagittal link):
![SagittalAccidentals](https://user-images.githubusercontent.com/1655500/99117768-99f3b400-25f6-11eb-8106-bc3ecbc78c0f.png)
Sagittal accidentals apply to _band-widths_ of alteration, so the interpretation would be limited to the frequencies in the middle of those band-widths at Olympian precision. (Have I understood this correctly?)
If, as I think, the alteration at Olympian precision is standardized, then we don't _need_ a `cent` or `frequency` attribute at all!

But a `cent` or `frequency` attribute could _still_ be used to override the meaning of the printed (standard or Unicode) accidental(s):
```
<note pitch="Gqb4" accidentalGlyph="U+E303" cents="-21.506"/>
```
or
```
<note pitch="Gqb4" accidentalGlyph="U+E303" frequency="380.4"/>
```
The `cents` attribute would be the deviation from equal temperament G4. The `frequency` attribute would override (=ignore) the notated pitch altogether, Unicode or otherwise. This could be a useful scenario when including _exact_ pitch information in a score that uses low precision pitch notation or whose real pitches are difficult to program for one reason or another... (e.g. [Turkish folk music accidentals](http://www.smufl.org/version/1.2/range/turkishFolkMusicAccidentals/)). There are so many specialised accidentals defined in SMuFL that its difficult to imagine client software being written to cope with them all individually.
Unfortunately I can't see any way to ensure that applications perform Sagittal notation correctly (with or without a frequency attribute) -- but having one would certainly make the applications' job easier. Maybe we just have to rely on the applications' advertised capabilities...

BTW: Your vision of an editor that uses Sagittal-like, cumulative accidentals sounds very plausible. But I think three levels of precision ought to be enough! :-)

**Comment by cmloegcmluin** [comment]
Ah, I think I get it now. Thank you for taking the time to explain so clearly.

> If the application supports playback of the score, it could infer frequencies using the basic (standard equal temperament) G4 and an alteration due to the Sagittal accidental(s).

> Unfortunately I can't see any way to ensure that applications perform Sagittal notation correctly (with or without a frequency attribute) -- but having one would certainly make the applications' job easier. Maybe we just have to rely on the applications' advertised capabilities...

So it's up to the application to find those Sagittal glyphs specified by their Unicode codepoints, and know what to do to the pitch and bar canceling, etc. That's actually not so bad. I don't think any do it now, but that's just the sort of thing I could write a [MuseScore plugin](https://musescore.org/en/handbook/plugins) for.

> Sagittal accidentals apply to _band-widths_ of alteration, so the interpretation would be limited to the frequencies in the middle of those band-widths at Olympian precision. (Have I understood this correctly?)

You're very close. It's _slightly_ more complicated than that. Each of those band-widths, or "capture zones" as we call them, has a default value, or "primary comma", which is not necessary at the middle of the zone, but somewhere inside (that all depends on the chaotic irregularities in distribution of important commas in pitch space, among other factors). 

> If, as I think, the alteration at Olympian precision is standardized, then we don't _need_ a `cent` or `frequency` attribute at all!

Yes, I think you're right, then. That default value is the standardized alteration for the symbol, whether being interpreted by a human reading it off the page, or a computer processing the markup. It is acceptable for the symbols to represent an alteration of any of the "secondary commas" inside its capture zone, but in that case the composer must indicate it somehow else — in a key, or whatnot. So in that case they'd be expecting to have to do a bit of manual tweaking anyway, so it's a non-issue.

> The `cents` attribute would be the deviation from equal temperament G4.

Here's where it gets a little tricky. You may notice that none of the commas indicated in the diagram you've inlined above include any 2's or 3's in their name's prime factorization (e.g. 7:11k, 25C, etc.). That is because Sagittal commas represent pitch alterations relative not to standard 12-tone equal temperament, but to a chain of Pythagorean fifths (frequency ratio 2:3). In other words, the chain of fifths takes care of the 2's and 3's, then these commas take it from there. In pure JI, we use exact 2:3 fifths, but if you're composing in a particular equal division of the octave then its fifth will be tempered, sometimes several cents off from pure. So it would only be in the case that you were using Sagittal's "Trojan" notation — which uses equal divisions of the octave which are multiples of 12 and thus have the same 700 cent fifth as in standard tuning — that you could get away with notating relative to the default values of the pitches (which is Trojan's main advantage and raison d'être). 

But I'm pretty sure handling all this would have to be the job of the requisite plugin per digital music notation application that we'd need to develop and maintain. Certainly Sagittal's notations are not the only microtonal notations which follow these principles, but I won't hold my breath for this functionality to come with MuseScore and its ilk by default. Please correct me if I'm wrong and this is not the sort of problem a plugin could solve.

> BTW: Your vision of an editor that uses Sagittal-like, cumulative accidentals sounds very plausible. But I think three levels of precision ought to be enough! :-)

The rows of the above diagram _do_ correspond to different precision levels, but there doesn't happen to be a 1-to-1 correspondence between how many accidental glyphs are required to notate a pitch and which precision level you're using. If you're curious I can explain more offline; it may not be pertinent to the current discussion.

**Comment by notator** [comment]
>> The cents attribute would be the deviation from equal temperament G4.

> Here's where it gets a little tricky. 

That's why I was wondering if it might be better to have a(n absolute) `frequency` attribute rather than (relative) `cents`. The `cents` attribute is actually sub-optimal when used in conjunction with Sagittal's default pitches and use of cents. Actually I can't see why it would need to be used at all given Sagittal's out-of-the-box precision.
A `frequency` attribute, if provided in the markup, could either
- be ignored (if the application doesn't trust it), or
- be used to override the default frequency of any accidental that has one, or
- be used to provide a frequency for an accidental whose precise meaning is unknown. 

A specialised Sagittal editor (plug-in) could, for example, ignore `frequency` attributes when importing scores, but write them when exporting. Then non-specialised applications would still be able to play the score correctly.

**Comment by cmloegcmluin** [comment]
> That's why I was wondering if it might be better to have a(n absolute) `frequency` attribute rather than (relative) `cents`.

I see now. The salient distinction being absolute v. relative. Yes, then, I agree that `frequency` is the way to go.

So the most important thing is just allowing MNX to get all the glyphs/accents on the page, so the plugin can find them and figure out which absolute frequency to put there. And the colon separated string will accomplish that well. 

FYI: I realize I may have diluted this fact earlier, but it is indeed the case that Sagittal sometimes _does_ have three accidentals on a single note. And in its Prime Factor notation, specifically, it can have even more.

**Comment by x31eq** [comment]
Hello MNX project!  I was directed here by social media.  I have many years of experience with microtonality and I wrote some extensions to LilyPond to get microtonal notations working, including extended Helmholtz-Ellis.

I can attest that Helmholtz-Ellis has a following, that people try to get it working with LilyPond, and that other people are working on extensions for other packages.  So I agree with the conclusions here that a standard supporting multiple glyphs would be a good thing, although it brings in complications.  I think the colon syntax is a bit clumsy, though.  It may be consistent with other parts of MNX, but it looks like embedding a syntax in the XML attributes instead of encoding the semantics in XML itself.  Maybe MNX is an XML format for people who don't like XML, I don't know.  Anyway, I came up with this alternative:

```
<note pitch="G" nominal-frequency="391.111" frequency="386.270">
    <accidental cents="-21.506" glyph="U+E303" ratio="80:81">b4</accidental>
</note>
```

Advantages of this way: it simplifies the chromatic pitch system to only worrying about chromatic pitches.  It helps an _editor_ work out what to do if an accidental is deleted (so far the talk has been about displaying the score correctly, which is the most important thing, and making sound of it, which is also important).  It gives a hint as to the meaning of the accidental with the ratio, which can be useful for either JI or tempered music.  A reader that doesn't understand the tuning information can safely ignore it because the absolute frequency is still there.  The accidental tag is also something that could be used in a list of standard meanings, which would be useful for editors.

The frequency can be considered an advisory, like metronome marks.  There's a problem with microtonal notation that once you put exact frequencies in to multiple decimal places, people thing they should be obeyed exactly.  Having the ratio in there as a semantic hint gives some information for making a choice in interpretation.  Another thing I randomly remembered: there are notations that show cents deviations as numbers relative to chromatic or quartertone pitches, and they should be supported.

As an example of a double-accidental with a made-up glyph:

```
<note pitch="G" nominal-frequency="391.111" frequency="387.994">
    <accidental cents="-21.506" glyph="U+E303" ratio="80:81">b4</accidental>
    <accidental cents="7.711" glyph="U+E123" ratio="225:224">sk</accidental>
</note>
```

The order matters, and I think accidental glyphs should be added right-to-left, but at least that has to be standardized.  To anticipate an objection, this might not be consistent with the way "note" is defined in the core spec, so maybe there should be a different tag for the advanced case.

Another idea would be to include the tuning of the accidentals as part of the chromatic pitch:

```
<note pitch="G-0.108w" frequency="386.270">
    <accidental cents="-21.506" glyph="U+E303" ratio="80:81">b4</accidental>
</note>
```

I'm not sure how the "tone" is defined for chromatic pitches.  I calculated this relative to 200 cents.  Now we have tones as a unit, maybe the accidental shift should be specified in tones rather than cents to avoid proliferation of units because my proposal ended up using tones, cents, and frequencies.

**Comment by notator** [comment]
@x31eq Welcome! The more input we get here from the microtone community, the better! :-)

Before replying to your post, I'd like to say a bit more about MNX's current approach to displaying and performing `<note>` elements:
- How to code whether an accidental is displayed or not
- Transposing instruments (e.g. Horn in F)
- Ottava markings

and propose a methodology for dealing with "advanced" capabilities in the [MNX Draft Specification](https://w3c.github.io/mnx/specification/common/):
I think that capabilities that the co-chair decides don't belong in basic MNX should be included in the Draft Spec anyway, and that they should be clearly labelled there as being "advanced". They might have lower priority for inclusion in _MNX by example_, but they need to be _tracked_ so that the basic format can be defined with them in mind.
 
**How to code whether an accidental is displayed or not:**
MNX currently decides whether an accidental is displayed/printed or not using the existence or otherwise of an `accidental` attribute. See [MNX by example: accidentals](https://w3c.github.io/mnx/by-example/#accidentals). This is a slightly open issue that hasn't been mentioned in this thread yet.
@mdgood says (in https://github.com/w3c/mnx/issues/180#issuecomment-627511829):
> Although the current version of the [MNX] spec tries to make this easier with an optional accidental attribute, the design of that attribute could likely be improved. For example, we might make the special value "auto" the default, so that the attribute is only needed for forced, alternate, or hidden accidentals.

My feeling is that we can ignore the forced, alternate and hidden display types for the moment, since MNX is defined _part-wise_. We may need to revisit the situation when defining system breaks (Issue #185)) and/or _cautionary_ accidentals (accidentals written in brackets).
So, for the moment at least, I'd prefer MNX's `accidental` attribute to be even simpler: a simple _boolean_ that needs no value. If the `accidental` attribute is present, the accidental glyph (Unicode or not) is printed in the score, if not, not. (The attribute's name could be shortened to `acc` if it seems too long.)
In the following example, both pitch attributes are "Db5", but the accidental is only printed next to the first notehead. 
```
...
    <event value="/4">
        <note pitch="Db5" accidental/>
    </event>
    <event value="/4">
        <note pitch="Db5"/>
    </event>
...
```
The `<note> pitch` value is _always_ provided in MNX (12 or maybe 24-note scale) but the accidental is often not printed -- for example when there is a key-signature in force. Client software can therefore _always_ derive a (default) frequency from the pitch value even when there is no printed accidental in the score.

**Transposing instruments**
If, for example, the score is a microtone composition written for Horn in F (written C5 sounds F4), then the application that writes a `frequency` value into the score needs to transpose the frequency it derives from the other info in the `<note>` down by 7 equal temperament semitones. The default transposition would, of course, be 0 semitones.
[§6.10.9 of the Draft Spec](https://w3c.github.io/mnx/specification/common/#the-transpose-element) says that transposition is done using a `<transpose>` direction inside a `<part><measure>`. 
[§6.10 of the Draft Spec](https://w3c.github.io/mnx/specification/common/#common-staff-directions) says that such staff directions
> apply from the start of that measure to all subsequent measures within the same [...] part element until changed.

But the transposition can also change _during_ a measure. (The score and horn parts of Wagner's _Siegfried Idyll_ change a lot like that!) As I understand the Spec, this can be done either by using the staff direction's `location` attribute ([§5.5. Measure location syntax](https://w3c.github.io/mnx/specification/common/#measure-location)), or by including the `<directions>` at a particular point in a `<sequence>` (See [§6.8. Direction content](https://w3c.github.io/mnx/specification/common/#common-direction-content) ).
As always, I'd prefer not to have two ways of doing the same thing. The first option more obviously applies to both staves, so I'd always put the transposition direction at the beginning of a `<measure>`, and the code would look like this:
```
    <part>
        <measure>
            <directions>
                <!-- optional location element (a "measure location") here -->
                <transposition>-7</transposition>
            </directions>
            <sequence> <!-- staff 1 -->
                <event ...>
                    <note pitch="Gqb4" accidentalGlyph="U+E30F:U+E30E" />
                </event> 
                ...                           
            </sequence>
            <sequence> <!-- staff 2 (this could be a synthesizer or a transcription of old organ music...) -->
                ...                
            </sequence>
        </measure>
    </part> 
``` 

**Ottava markings**
See [MNX by Example: Octave shifts](https://w3c.github.io/mnx/by-example/#octaves)
The text of [§4.12 Written pitches](https://w3c.github.io/mnx/specification/common/#written-pitch) needs to be reformulated so that its meaning is clearer (A "written pitch" cannot be a frequency!), but its clear that ottava markings don't need to be tracked by applications that calculate frequencies from the information in a `<note>`.

---
@x31eq:
So far in this thread, @cmloegcmluin and I have agreed that a note element could have the form:
```
<note pitch="Gqb4" accidentalGlyph="U+E30F:U+E30E" frequency="340.50" />
```
(I have no objection to using three or more glyphs.) For the (composite) glyph to be _displayed on a screen_ or _printed_, this also needs the `accidental` flag described above:
```
<note pitch="Gqb4" accidentalGlyph="U+E30F:U+E30E" frequency="340.50" accidental />
```
You say:
> I think the colon syntax is a bit clumsy, though. It may be consistent with other parts of MNX.

I quite like it. :-) It is indeed consistent with other parts of MNX. Even the `<note> pitch` value is a composite string that needs to be analysed. Its a case of balancing readability against functionality, and avoiding the unnecessary multiplication of entities (_pace_ Occam). If elements are created `ad lib.`, the file quickly gets bloated and unreadable. However: its _possible_ that we do after all need a separate `<accidental>` element. That could be necessary for _many_ separately printable objects so that they can be the subject of CSS styling (e.g. coloured text). But in this case, CSS attributes could also go in the `<note> accidental` attribute...
In this connection, it might be worth adding a similar `<note> notehead` attribute for defining coloured noteheads. AFAIK, the CSS styling of MNX elements has not yet been discussed 

>There's a problem with microtonal notation that once you put exact frequencies in to multiple decimal places, people think they should be obeyed exactly.

I'm not sure that I really understand this. Why is writing exact frequencies a problem? Presumably the software that _writes_ the frequency will avoid writing unnecessarily long decimals, and the software that _reads_ the frequency will do the best it can with the given value. See [the Wikipedia article on the "just-noticeable difference" between pitches](https://en.wikipedia.org/wiki/Pitch_(music)#Just-noticeable_difference). There's no way to stop information in XML files being used wrongly, but in this case the consequences don't seem very serious.

> Having the ratio in there as a semantic hint gives some information for making a choice in interpretation.

Anyone who specifies a particular Unicode glyph, already knows what it means, so should not need a hint in the file that's being written. Such a hint belongs in the glyph's documentation, not in the score. Again, if I'm not getting the whole story, please explain.

> there are notations that show cents deviations as numbers relative to chromatic or quartertone pitches, and they should be supported.

We're defining a new notation format here, so we don't need to support other formats. That's the job of conversion software. The proposals outlined above for MNX can store the result of calculating frequencies as cent deviations from chromatic or quartertone pitches so, in a sense, we do support that. Conversion is possible.

Hope that helps! Many thanks again for writing. Feedback and dialog are very important! :-)

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
