### ISSUE TITLE
Define how to encode a collection of documents in a single MNX-Common file

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#188]

**Comment by notator** [comment]
@adrianholovaty
Its not clear to me what this issue is about. (MNX-Common files don't actually exist.)
If its about the different scores that can be contained in an `<mnx-common>` element, then the title needs to be changed to:
"Define how to encode a collection of scores in a single `<mnx-common>` element"
and the answer is:

According to [the current proposal for grouping parts](https://github.com/w3c/mnx/issues/185#issuecomment-643174127), a full score and its parts can be defined as separately printable `<score>` objects inside a single `<mnx-common>` element.
Both the context and content of `<score>` elements are defined in [the proposal](https://github.com/w3c/mnx/issues/185#issuecomment-643174127).

So there's nothing to add here.

On the other hand, maybe this issue is saying that the proposal needs to be made into an official, evolving document subject to Pull requests. I think that would be a good idea. There have been a number of proposed changes, and it would be helpful if we could all agree on its latest state.
If it is to become an official document, then I think it should cover the structure of a whole MNX file, not just the `<mnx-common>` element (see https://github.com/w3c/mnx/issues/185#issuecomment-640018187).

**Comment by shoogle** [comment]
Presumably this issue is about we call "albums" in MuseScore. These can be used for:

- A ***multi-section work*** (e.g. an opera or symphony, or something larger like Wagner's Ring Cycle)
- A ***playlist*** of distinct pieces (e.g. songs from a particular concert or revue)

In the former case, sections appear in a well-defined order to form the larger narrative. Instrumentation is likely to be the same or similar across the whole work. If a user decides to swap the flute for a piccolo in the first movement of a symphony then they would probably expect the same to happen in later movements.

In the latter case, the pieces are independent of each other, and instrumentation may vary greatly. Users probably wouldn't expect changes made to one of the songs in the playlist to apply to other songs. The pieces may have an order, but it is arbitrary: other orderings are equally valid.

**Comment by notator** [comment]
@shoogle I don't think it can be that. The `<mnx><collection>` element is already defined to deal with such things (and more). 
```
<mnx>
    <collection>
        <score>
            <title>Act I Scene 1 Götterdämmerung</title>
            <mnx-common>...</mnx-common>
        </score>
        <score>
            <title>Act I Scene 2 Götterdämmerung</title>
            <mnx-common>...</mnx-common>
        </score>
        <!-- etc. the rest of Götterdämmerung -->

         <!-- The xml-definition of mnx-braille and other notations, is forseen but has not yet begun. -->
        <score>
            <title>Act I Scene 1 Götterdämmerung</title>
            <mnx-braille>...</mnx-braille>
        </score>
    </collection>
</mnx>
```
And the co-chair is currently wanting to concentrate on `<mnx-common>` internals. Its a mystery.

**Comment by clnoel** [comment]
@notator I think that this is in response to the issues you raise in [issue #185](https://github.com/w3c/mnx/issues/185#issuecomment-643594264)

> But hows about renaming the outer `<score>` instead? We are proposing changes to [**§6.1.3 The _collection_ element**](https://w3c.github.io/mnx/specification/common/#the-collection-element) anyway: We now have `<part>`s defined inside `<mnx-common>`, so the `<collection>` "parts" type is redundant.
> I think the outer `<score>` element could be renamed **`<book>`**. (A "score" is a sub-class of "book"). Then we could have a `<collection type="text">` that would be a text (like the booklet in a CD) that provides ancillary information about the score. The text could, for example, contain links to related documents on the web. I don't think such info belongs in a score's metadata. Metadata should be self-contained info that only relates to the score itself.
> [begin Edit 13.06.2020]
> For the new issue: If the outer `<score>` element were to be renamed `<book>`, then the `<collection>` element itself could be renamed `<books>` -- which is both shorter and more precise. :-)
> Do `<collection>` elements really need to be nestable?

Perhaps the issue should be renamed if this is the case, becasue you are correct that we do not have "mnx-common files" we have "mnx" files, that were allowed (last I new) to have different mnx styles in them!

If that is the case, then I have to say that I find our current system to be plenty clear, except for need to differentiate the tags that you name `<score>` and I named `<scoreLayouts>` in #185 and #57

The only other thing `<collection>` needs is to fill out what "types" we support.

**Comment by notator** [comment]
I think this issue is obsolete, and could simply be closed.
There was some confusion here because it was opened before we had officially decided to have MNX-Common (aka MNX) files.
The answer, for MNX files is (as I suspected [above](https://github.com/w3c/mnx/issues/188#issuecomment-649396698)),

> According to [the current proposal for grouping parts](https://github.com/w3c/mnx/issues/185#issuecomment-643174127), a full score and its parts can be defined as separately printable `<score>` objects inside a single `<mnx-common>` element.

**Comment by notator** [comment]
Note that the MNX `<collection>` element was removed from the Draft Spec last October.
There is now a concrete example at https://github.com/w3c/mnx/issues/185#issuecomment-780403076 showing how full-score and part-booklets can be encoded in the same file.

**Comment by adrianholovaty** [comment]
Closing this because it's been solved by our new(ish) layouts system.
