### ISSUE TITLE
Rename MNX-Common to MNX?

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#191]
Originally the "MNX" name was conceived as an umbrella term to support many types of music notations. MNX-Common would be for common Western music notation, MNX-Generic would be for graphical encodings of music, etc.

MNX was also intended to be a temporary codename, until we decide on a more "proper" name for the format.

By now it's been a few years and, as MNX-Common has been more deeply developed, I believe it's come time to make a final decision on the naming. We broached this subject in the April 2020 community group meeting ([meeting minutes here](https://www.w3.org/community/music-notation/2020/05/04/2020-online-meeting-minutes/)).

There seems to be consensus that we should stick with the name MNX in some form ("MNX-Common," "MNX-Generic," etc.) — but there's also a sense that giving _multiple_ formats subtly different MNX names would result in confusion once our new formats are in use in real-world music notation applications.

So here are the options, as I see it:

1. Use MNX-Common and MNX-Generic
2. Rename MNX-Common to MNX, MNX-Generic to MGX, and find other (short) names for other future MNX-family formats

Arguments for using "MNX-Common":

1. The MNX-Common and MNX-Generic names have been used for several years now.
2. Having a shared common "MNX-" prefix will help people understand these formats have a shared philosophy.

Arguments for using "MNX":

1. MNX-Common is wordy, and people will naturally shorten it to MNX (which has already been happening) — leading to confusion. (If MNX-Common gets shortened to MNX, what does MNX-Generic get shortened to? MNX as well?)
2. In practice, MNX-Common and MNX-Generic have very little in common, so keeping a unified name is more confusing than beneficial. It is completely possible and reasonable for this community group's future formats to share philosophy and design while having separate/unrelated names.

For the record, my vote is strongly for MNX instead of MNX-Common. Some prior discussion is in [this issue](https://github.com/w3c/mnx/issues/98).

**Comment by dspreadbury** [comment]
A further argument for using "MNX" for MNX-Common and something different for MNX-Generic and other future formats in the MNX ecosystem, eruditely expressed by @adrianholovaty in the past and worth reiterating here, is that consumers need to have a clear idea about what they can do with an MNX document. If we use the same name, or even the same prefix, for different flavours of MNX documents, consumers will not know whether a given application can work with a particular file. Even implementors may experience the same confusion.

**Comment by samuelbradshaw** [comment]
I think people would get "MNX" and "MGX" mixed up too – for MNX-Generic, I would recommend doing "GMX" or something similar (I think people notice differences in the first letter more than the middle letter).

**Comment by samuelbradshaw** [comment]
People may get "MNX" and "MGX" mixed up too – I think people could distinguish different formats better if it's the first letter that changed instead of the middle letter. How about .cmx and .gmx?

**Comment by notator** [comment]
Unfortunately, I wasn't able to say what I was thinking on this subject at the Zoom meeting (my mike wasn't working), so I subsequently posted Issue #175. (I've now closed that issue as a being a duplicate.) Here's an updated precis:

- If we are going to rename the file types, we also need to think about how we want to name MNX-Common **profiles** -- for which there are important use-cases.
- The "standard" profile is the format that is the successor to MusicXML. It would be useful to have one or more simpler profiles that could be implemented by lightweight/cheaper software for use in (e.g.) education, simple church-choir music etc. Other profiles might well include notations such as Makam music (see #189) that don't need nested tuplets, but maybe need more support for special accidentals/frequencies etc.. 
- Each profile must, of course, have a unique extension (so that we don't have to look inside the file to know what format its in): A possible solution would be to follow the .mp3/.mp4 paradigm, and give each profile a numerical suffix. If we follow @samuelbradshaw's suggestion of using ".cmx" for the standard profile, then the other profiles could be ".cmx1", ".cmx2" etc.
- Other MNX file types (XML formats for describing structured music notation) could have other extensions (e.g. ".bmx" for Braille, ".hmx" for Hamparsum, ".kmx1", ".kmx2" etc for different profiles of a Korean notation etc.). Having an "mx" in each extension might be a way to suggest "corporate identity", - but in principle all the extensions could be allocated arbitrarily/unsystematically.
---

I agree very much that we need to sort the file names out, but think this issue cuts more deeply than expected. I also think that this would be a good time to simplify things by shedding some ballast. As I see it, the issues are, in reverse order of importance:

1. MNX-Generic has failed and should be abandoned.

This means we don't need to think about its file extension. MNX-Generic  (originally GMNX in the [Group Charter](https://www.w3.org/community/music-notation/wiki/Group_Charter)) was envisaged for "applications that do not depend on particular notational systems or their semantics". In fact, this means that it has nothing particularly to do with music notation, so it should really be out of scope for this CG. The [MNX-Generic Draft Spec](https://w3c.github.io/mnx/specification/generic/) is not really a specialised file format at all. It actually describes a _**technique**_ for combining unstructured graphics with temporal information, and that technique can be implemented using existing standards (see my realisation of the [Lutoslawski example](http://james-ingram.de/demos/scoreAudioSynchDemo/oggPng.html)), so there's no need to define anything new at all.
Ideally, MNX-Generic (aka GMNX) should be replaced in the Group Charter by something that says that, following the completion of the MusicXML replacement, this CG will be the place for developing XML representations of all the world's other music notations (including Braille, Medieval, Arabic and Asian music notations).

2. If MNX-Common is renamed MNX, then what happens to the original MNX?

There is a distinct problem with keeping the original MNX container: _There's no way to define a file extension that describes its content._ I'd be quite happy for it to disappear and be replaced by the use of a compressed .zip folder.
I've never really understood why the original MNX container existed, but suspect that its original purpose had something to do with including scores and parts in the same file. (We now have a different solution to that problem.) If the MNX container were to disappear, then
- we would be free to rename MNX-Common as mnx.
- we ought to simplify an MNX-Common file's internal structure by removing the outer `<mnx>` layer.

If, for the sake of argument, we used ".cmx" as the file extension, and `<cmx>` as the element name, then we can replace:
```
<mnx>
    <collection>
        <score>
            <title>Symphony, Movement 1</title>
            <mnx-common profile="standard">...</mnx-common>
        </score>
        <score>
            <title>Symphony, Movement 2</title>
            <mnx-common profile="standard">...</mnx-common>
        </score>
    </collection>
</mnx>
```
by a zipped folder containing two ".cmx" files having the form: 
```
<cmx profile="standard">
    <title>Symphony, Movement 1</title>
    <globals>...</globals>
    <parts>...</parts>
    <systemLayouts>... <systemLayouts>
    <!-- etc -->
</cmx>
```
This is the same structure as proposed in https://github.com/w3c/mnx/issues/185#issuecomment-643174127, except that `<mnx-common>` has been replaced by
`<cmx profile="standard">`, and the `<title>` element has been moved inside the `<cmx>`.
Issue: Is there anything else that needs to be moved inside the `<cmx>`? Metadata, for example...

The zipped folder (".zip" extension) could, of course, additionally contain any other material, including scores and parts written in other profiles or formats.

I have no strong feelings about the string used to replace "mnx-common", but rather tend away from "mnx" because it seems to imply that CWMN is the only and ultimate music notation -- which is a bit odd if we then start to add profiles...
I quite like "cmx" (as used above), but could imagine other alternatives: "mxl" might be a nice reminder that this format is the successor to MusicXmL. "mxl" could be privileged by being the only format that _begins_ with an "mx"...

**Comment by bhamblok** [comment]
My 2 cents here, I like both the letters **M** and **N** from "**M**usic**N**otation" in the naming of the format. Because, that's what we are trying to specify here, aren't we?  
So I would like to have the "corporate identity" to include "mn", rather than "mx".
I always thought MNX stood for **M**usic**N**otation**X** where X can be anything, being specified any further in future.
cmn or gmn (and hmn, bmn, kmn) are all fine by me, or should it be mnc, mng, mnh, mnb, mnk, ... ?

**Comment by notator** [comment]
I just wanted to add that I now think that MNX-Common should definitely **_not_** be renamed MNX.
As @adrianholovaty  said:
>Originally the "MNX" name was conceived as an umbrella term to support many types of music notations. MNX-Common would be for common Western music notation,...

If MNX-Common were renamed MNX, then:
- this repository's name would have to be changed to reflect the fact that it contains much more than just the history of MNX-Common
- many of our previous comments would change their meaning, leading to endless confusion.

So I'm definitely supporting [@bhamblok's latest comment above](https://github.com/w3c/mnx/issues/191#issuecomment-662950175): 
>cmn [...] (and hmn, bmn, kmn) are all fine by me

**Comment by notator** [comment]
Sorry this is coming in instalments...

Okay, so assuming that
- MNX remains the name of this repository, and it continues to be responsible for all the music notations in scope.
- There are no ".mnx" files because that name can't describe the content of files that have arbitrary content. A zipped folder does that job well enough.
- MNX-Common is renamed CMN (CommonMusicNotation), and will have its own file type. A CMN file has the extension ".cmn". Its first internal element is `<cmn>`.

@adrianholovaty Am I right in thinking that Issue #188 should now be re-titled "Define how to encode a collection of documents in a single CMN file"? That issue caused a lot of confusion when it appeared, but it makes more sense in that form.
I think it would be best to close #188 now, and provide the possible definition here, since it presupposes the renaming.

It would be quite possible to define CMN files (extension ".cmn") containing a collection of documents as follows:
```
<cmn profile=standard>
    <collection>
        <score>
            <title>Symphony, Movement 1</title>
            <globals>...</globals>
            <parts>...</parts>
            <systemLayouts>... <systemLayouts>
            <!-- etc -->
        </score>
        <score>
            <title>Symphony, Movement 2</title>
            <globals>...</globals>
            <parts>...</parts>
            <systemLayouts>... <systemLayouts>
            <!-- etc -->
        </score>
        <!-- etc. more scores -->
    </collection>
</cmn>
```
This is very like the original `<mnx>` container definition [(see above)](https://github.com/w3c/mnx/issues/191#issuecomment-662941638), except that **all** the contained `<score>` elements are CMN scores, so their type does not have to be re-declared inside each `<score>`.
I think that both the `<collection>` and `<score>` elements should be optional, so that the following would also be a valid CMN file:
```
<cmn profile=standard>
    <title>Symphony, Movement 1</title>
    <globals>...</globals>
    <parts>...</parts>
    <systemLayouts>... <systemLayouts>
    <!-- etc -->
</cmn>
```
Further thoughts:
1. §6.1.1 of the Draft Spec defines an optional `<head>` element for `<mnx>`. I think this should be carried over into the definition of `<cmn>`. `<head>` contains metadata and a `<stylesheet>` element. These need to be reviewed later.
2. If we agree that profiles (if any) are going to have names with integer suffixes (CMN1, CMN2 etc), then the `profile` attribute becomes redundant. File content could just be:
   - CMN: `<cmn>...</cmn>`, extension ".cmn"
   - CMN1: `<cmn1>...</cmn1>`, extension ".cmn1"
   - CMN2: `<cmn2>...</cmn2>`, extension ".cmn2"
   - BMN: `<bmn>...</bmn>`, extension ".bmn" (Braille)
   - etc.

**Comment by adrianholovaty** [comment]
@notator I'm afraid that's drifting quite a ways off topic...! Please keep this discussion tightly focused on the naming.

**Comment by notator** [comment]
@adrianholovaty If you rename #188, I can move the above comment there. Or shall I start a new issue on what I think the subject should be?
What do you think about the renaming proposals supported by myself, @bhamblok and @samuelbradshaw ?

**Comment by shoogle** [comment]
I support renaming MNX-Common to MNX. Potential users are already calling it that, and I'm sure everybody here has been guilty of that mistake at least once.

Re. MNX-Common profiles, containers, file extensions, etc. None of these are in use at the moment, so it doesn't matter what we do with them (or at least they are not relevant to this discussion). However, the name "MNX" is already in use to refer to MNX-Common, so me might as well make it official.

> this repository's name would have to be changed to reflect the fact that it contains much more than just the history of MNX-Common

We haven't done nearly as much work on MNX-Generic so I see no reason to rename this repository.

> I always thought MNX stood for MusicNotationX where X can be anything, being specified any further in future.
cmn or gmn (and hmn, bmn, kmn) are all fine by me, or should it be mnc, mng, mnh, mnb, mnk, ... ?

Users already refer to MNX-Common as just MNX, so I think it's too late to use "MNC" or "CMN". (Also, MNC doesn't sound as good as MNX, and CMN is too similar to CNN.)

"MNG" might be appropriate as the new name for MNX-Generic (and it needs a new name because it is confusing for users if MNX can be used to refer to anything other than MNX-Common) but that's not really relevant to this discussion about what to call MNX-Common.

**Comment by notator** [comment]
My thoughts on this subject are developing as a result of this discussion. Here's what I'm currently thinking:

1. I'm very much in favour of defining a file type for MNX-Common's standard profile. The standard profile is the replacement for MusicXML, and is the format we're currently working on. Prime candidates for the file extension are currently ".mnx" and ".cmn", but other alternatives can't yet be ruled out. The file type will also be its colloquial name (e.g. MNX) and the name of the file's root element (e.g.`<mnx>`).
2. "MNX-Common" should remain the generic term for all the CWMN profiles. That would mean that neither the name of the "MNX-Common Draft Spec" nor the "MNX-Common" labels on many of the issues in this repository need be changed.
3. I now agree with @shoogle that the choice of name will not restrict our ability to define names for other MNX-Common profiles or indeed any other notations. The sky won't collapse if the chair decides to use MNX, but I would still prefer CMN (or maybe some other string) because:
   - Redefining MNX is like re-writing history. It shouldn't be done. The term was defined in our Group Charter, so has been in use too long for its meaning to be changed.
   -  CMN is a more accurate abbreviation for CWMN than MNX, so it should be more comfortable to use in the mid to long term. A compromise solution might be CMX...
4. Whichever name is chosen, the existing `<mnx>` element in the MNX-Common Draft Spec ought to be moved out of the file, since it is not a component of any MNX-Common profile. This could/should have been done at the same time as MNX-Generic was moved out. I see two alternatives:
   - Rename it, possibly to `<mnx-container>`, and put it in a separate MNX-Container Draft Spec. 
   - Delete it completely. MNX-Container can be replaced by a zipped folder, so that's what I would do.

**Comment by samuelbradshaw** [comment]
I agree with @notator's preference in file naming.
- If we have users referring to "MNX-Common" as "MNX", it's because we 1) haven't defined a shorter abbreviation, and 2) haven't been consistent in making a distinction between the two – it's not because MNX is a better abbreviation for CWMN.
- Because MNX and MNX-Common aren't finalized, our existing users are a small group. Any of them who are making serious plans to use MNX at this point, are in the loop of these kinds of discussions, so they will be able to adapt to changes more easily than our potential future users. Because of that, a decision we make should take into account our future potential users, more than our existing users (if we have to choose between the two).
- For our potential future users, it will be easier to market the format if it has a name, abbreviation, and description that match – it makes it simple and provides repetition, so users will remember it better: "The Common Music Notation (CMN) file format is a standard for encoding common western music notation in a way that can be shared between digital music applications." The fact that MNX doesn't have a clear expanded name makes it hard to market. Easy to advertise = faster adoption.

I originally proposed CMX above, but now I'm leaning towards CMN because of how nicely it expands to "Common Music Notation." It's simple, and for a generic future user who hasn't heard of MNX before, it makes sense.

**Comment by notator** [comment]
@samuelbradshaw All points agreed. You said:
> (As a note: "cmn" is also the ISO 639-3 abbreviation for Chinese Mandarin, but with three letters, it's hard to avoid overlap with something. The first result in Google for "MNX" is MNX Global Logistics. "CMX" is being used by CMX Cinemas...)

(In #175) I originally suggested CMN as a possible name for the standard profile, because it is CWMN without the W. In the same posting, I also mentioned the possibility of using CMN1, CMN2, CMN3 etc. as the names of the other profiles.
If we went for _four_ letters for _**all**_ the profile names, the standard profile could simply be CWMN (with ".cwmn" and `<cwmn>`), while the other the profiles would still (potentially) be CMN1, CMN2 etc.
Disadvantages of using ".cwmn" are that it is one character longer (more typing), and that its more difficult to say.
Advantages are that its unique and very precise, and everyone in the community knows immediately what it means (marketing point).
In practice, such extensions are rarely typed by users, and are used far more often in written than in spoken form, so I think the disadvantages would actually be quite small.

**Comment by mdgood** [comment]
In general I agree with @shoogle's post above but I want to elaborate on a couple of points.

Although the number of people familiar with the MNX name is small relative to who will use it in the future, it is an important group - the developers who are the first group that will make or break the success of the format. I don't think years of MNX branding and awareness is something to throw away lightly. Although in theory MNX was describing a container format for all notations, most of the work by far has been on MNX-Common. I believe that redefining MNX to mean what we now call MNX-Common should help clarify things to our target market of developers, rather than confuse things.

I think that whatever name we choose should be branded in some way. So "mnc" would work better than "cmn" because "cmn" is already abbreviation for what MNX-Common represents. (But I agree that "mnx" sounds better - and is easier to speak with its consistent vowel-consonant alternation.) The "mxl" name is already used for a MusicXML file extension and as a MusicXML abbreviation, so I think that would be confusing.

**Comment by adrianholovaty** [comment]
Thanks to everybody for chiming in!

The comment that resonated with me most strongly was [this one](https://github.com/w3c/mnx/issues/191#issuecomment-663589735) from @shoogle. I agree with that 100%.

**Comment by adrianholovaty** [comment]
A follow-up here: we've just had our [biweekly co-chairs meeting](https://www.w3.org/community/music-notation/2020/08/04/co-chair-meeting-minutes-august-4-2020/) and discussed this. We've made the decision to rename MNX-Common to MNX. Here's what will change:

* MNX-Common gets renamed to MNX throughout our documents (GitHub, MNX By Example, specs)
* MNX-Generic (temporarily) becomes nameless, as something like "general proposal for representing music scores as graphical elements with linked audio and performance data" (we're kicking the can down the road until we prioritize working on this format)

Thanks again to everybody who contributed thoughts to this discussion!

**Comment by shoogle** [comment]
Thanks for this @adrianholovaty! Regarding a temporary name for MNX-Generic, I'm putting in a vote for "Teh generic format".

**Comment by notator** [comment]
@adrianholovaty Have you considered what to do with the `<mnx>` element currently inside the MNX-Common Draft Spec.?

**Comment by adrianholovaty** [comment]
@notator: Yes, I think keeping the top-level element called `<mnx>` would make sense. I'd like to remove the concept of profiles as a further simplification, but that's an unrelated issue.

**Comment by notator** [comment]
There are at least three alternatives (leaving profiles aside for the moment).
Which of these, if any, are you going for?
1. Using `<mnx>` for both the container and the MusicXML replacement:
```
<mnx>
    <collection>
        <score>
            <title>Symphony, Movement 1</title>
            <mnx>...</mnx>
        </score>
        <score>
            <title>Symphony, Movement 2</title>
            <mnx>...</mnx>
        </score>
    </collection>
</mnx>
```
2. Deleting the original `<mnx>` container, and restricting all formats to the MusicXML replacement:
```
<mnx>
    <collection>
        <score>
            <title>Symphony, Movement 1</title>
            <globals>...</globals>
            <parts>...</parts>
            <systemLayouts>... <systemLayouts>
            <!-- etc -->
        </score>
        <score>
            <title>Symphony, Movement 2</title>
            <globals>...</globals>
            <parts>...</parts>
            <systemLayouts>... <systemLayouts>
            <!-- etc -->
        </score>
        <!-- etc. more scores -->
    </collection>
</mnx>
```
3. As above, but not including collections of documents in the file.
```
<mnx>
    <title>Symphony, Movement 1</title>
    <globals>...</globals>
    <parts>...</parts>
    <systemLayouts>... <systemLayouts>
    <!-- etc -->
</mnx>
```
If its none of these, could you provide a sketch of what you are intending?

**Comment by adrianholovaty** [comment]
@notator I do not have a strong opinion on any of those (and haven't given it much thought yet). That's a separate issue from the MNX renaming, as I see it.

**Comment by notator** [comment]
@adrianholovaty Its definitely _**not**_ a different issue from the MNX renaming! If you don't decide what to do with the existing MNX object before naming something else MNX inside the same file, chaos is going to ensue...

**Comment by shoogle** [comment]
@notator, nobody is using the format yet...

**Comment by adrianholovaty** [comment]
Marking this as closed now, as I've renamed MNX-Common to MNX throughout our various documents in the repo.
