### ISSUE TITLE
Pull request #208 (errors in the Draft Spec)

### ISSUE THREAD

**Issue by notator** [w3c/mnx#209]
I think PR #208 has been closed prematurely.
1. The errors in the Draft Spec that it addressed have not been corrected.
2. It contains a proposal (for adding an informative _MNX by Example_ for cross-staff beams), that should not simply be forgotten.

If the co-chair would like me to resubmit the corrections in smaller instalments, I could of course do that. (Instructions would help.)

**Comment by adrianholovaty** [comment]
@notator Good catch there, and sorry for closing #208 — that was unintentional! I think GitHub may have done it automatically when I deleted the beams-new branch, because #208 depended on it? At any rate, I will reopen and post a comment there.

**Comment by adrianholovaty** [comment]
My hunch was correct. GitHub closed #208 automatically because the beams-new branch was deleted. In fact it's impossible for me to reopen it...!

@notator I think the best way forward is to create a new pull request with the same changes, but applied to master instead of the beams-new branch. Lesson learned: Don't make a pull request on a temporary branch (such as beams-new was). If you still have your PR branch locally, you can create a new git branch from master, then apply your local branch's changes to your new branch.

**Comment by notator** [comment]
Yes, no problem, I thought something like that might have happened... :-)

I still have my beams-new corrections, so will do as you say, and
> create a new pull request with the same changes, but applied to master instead of the beams-new branch.

Since you can't re-open #208, I'll also open a fresh new issue to discuss the proposed _MNX by Example_ for cross-staff beams.

**Comment by adrianholovaty** [comment]
Sounds good. I agree it makes sense to keep the cross-staff beaming example a separate line of work.
