### ISSUE TITLE
Tuplet-definitions - how to determine the values?

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnx#22]
For a tuplet-definition like in MNX Proposal Overview of 26 April 2017 (5.3.6. Sequences - &lt;tuplet actual="3/8" normal="1/4"&gt;): How do you determine the values in the denominators? 
E.g. in 3/8 and 1/4 the values 8 and 4? Would 6/16 be the same as 3/8? And 1/4 the same as 2/8? It seems to me that only the ratio counts (ratio=3/2). 
Also the words "actual" and "normal" seem to me to be confusing. I should consider "actual" to mean the real value (sounding when played) in the music and not the graphic appearance (but this was the same in MusicXML).

How to determine these values 8 and 4 in like 3/8 and 1/4?

**Comment by joeberkovitz** [comment]
Agreed on the confusing names. The specification now uses the terms `inner` and `outer`. Please see https://w3c.github.io/mnx/specification/#the-tuplet-element

Ratios that are numerically identical do perhaps make a difference sometimes. In some editors and viewers tuplets can be optionally shown in a style where the full ratio is included in the tuplet label, as numerals followed by explicit note value symbols (e.g. "11 [eighth-note] : 6 [quarter-note]"). I've seen this style employed in rhythmically complex contemporary scores a number of times.  In this context, because the entire ratio is revealed to the musician viewing the score, it seems to be part of the compositional intent so it's important to preserve

In the case where the ratio never gets displayed, my current feeling is that the ratio is just an artifact of whatever choices the producer application made, and it shouldn't really matter whether the `outer` of an 8th-note triplet is 1/4 or 2/8.

**Comment by mogenslundholm** [comment]
The tuplets solution: "inner" and "outer" are really intuitive names. Good solution.
