### ISSUE TITLE
Change <directions> and <measure> to use distinct element names in different contexts

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#265]
MNX has two types of `<measure>` elements — [within `<part>`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-part/) and [within `<global>`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-global/). They both support `barline`, `index` and `number` attributes.

This strikes me as a bit of a design smell, because it's an opportunity for inconsistent data. It's possible to encode those attributes in both places with different values. Also, those three attributes really aren't part-specific, so I don't think we need to support them in the `<part>` version of `<measure>`.

So my proposal: let's remove the `barline`, `index` and `number` attributes from the `<part>` version of `<measure>`. They'd only be supported for the `<global>` version of `<measure>`, hence supporting One And Only One Way To Do It and keeping the data closer to its intended level of abstraction (global rather than part-specific).

Any thoughts/objections?

**UPDATE:** I've changed this issue's title to be more general. See discussion below.

**Comment by mdgood** [comment]
@adrianholovaty You can't do that in a W3C XML Schema. An element with the same name in the same namespace needs to have the same definition everywhere it's used. See https://www.w3.org/TR/xmlschema-1/#cos-element-consistent. If you want different definitions, the elements will need different names.

**Comment by clnoel** [comment]
So in global we get `global-measure` or `measure-definition` instead? I could go with that. We already disallow `sequence` in the global measures, so they already have different definitions.

**Comment by adrianholovaty** [comment]
@mdgood Thanks very much for pointing that out — that definitely impacts our solution here. Yeah, they already technically have different definitions (not in their attributes but in their allowed child elements, as @clnoel points out).

**Comment by joeberkovitz** [comment]
I'm agnostic on this point and happy to change the name of the global `<measure>` element if it makes the whole deal more schema-friendly.

Note that `<directions>` is allowed in both part and global measures. However its behavior is the same in both contexts so I think that's OK.

**Comment by joeberkovitz** [comment]
Uh, oops I think the two kinds of `<directions>` have different children. So maybe they need different names too.

**Comment by clnoel** [comment]
Also the `<directions>` inside a sequence have different children from either of the directions inside measure elements. Either we need to allow all the directions everywhere or we need to make the element names different. Argh.

**Comment by clnoel** [comment]
![image](https://user-images.githubusercontent.com/6453511/142068039-04b28a69-d625-472b-8d6f-b25313499a5d.png)

**Comment by clnoel** [comment]
Also, I can confirm the XML definition problem. I just tried to use the standard C# XML conversion on the Hello World MNX example, and it failed because "measure" is defined twice in the same namespace.

**Comment by adrianholovaty** [comment]
The [elements list page](https://w3c.github.io/mnx/docs/mnx-reference/elements/) is the best place to see this from a birds-eye view. It adds a parenthetical disambiguation for elements that are duplicated.

There are three types of `<directions>` elements and two types of `<measure>`. :-/

Yeah, these should get different names after all. I was kind of hoping it wouldn't be an issue, but we'd better bite the bullet and rename these. I've just changed this issue's title, as the scope of the problem is a bit different than originally reported.

**Comment by notator** [comment]
I feel, rather strongly, that @adrianholovaty should keep to his original intention, and _not_ change the names that @joeberkovitz originally chose. I think the names are very good as they are. Anything else just leads to unnecessary clutter.

@mdgood was quite right, of course, to point out that
> An element with the same name in the same namespace needs to have the same definition everywhere it's used.

But that's a bit misleading. The same name can be used in different contexts if it is given a different definition in those different contexts.
Here are two extracts from my current draft schema showing how
global/measure/directions is defined as a globalMeasureDirectionsType inside global/measure, and
part/measure/directions is defined as a partMeasureDirectionsType inside part/measure:
![globalMeasureDirections](https://user-images.githubusercontent.com/1655500/142453349-34d170c4-457f-4cf7-8c46-42548d896d53.png)
...
![partMeasureDirections](https://user-images.githubusercontent.com/1655500/142453391-124d38df-c892-4361-a954-be4b55c9eaa1.png)

@clnoel said
>  I just tried to use the standard C# XML conversion on the Hello World MNX example, and it failed because "measure" is defined twice in the same namespace.

The problem is in your code. You need "measure" either to be in two different C# namespaces, or (more likely) to be "measure" attributes of two different objects. My MNXtoSVG (a C# application) has no problem distinguishing between such objects.

**Comment by clnoel** [comment]
@notator This might be off topic, and I might have implemented this naively, but my C# objects are in different C# namespaces (MNX.Global.Measure and MNX.Part.Measure) and are on two different objects (MNX.Global.Global and MNX.Part.Part). However, I am not using a schema at all, as there is not official one published. I'm just parsing the xml as written using System.Xml.Serialization, and it came up with error I described.

So, I think we either need to have an official schema linked from our documentation that can be applied to the mnx documents, even while they're in development, or we need to rename the elements.

**Comment by mdgood** [comment]
@notator, are you validating against your draft schema or just parsing? It's during validation where the problem will appear.

**Comment by notator** [comment]
I was using my draft schema successfully to validate the example files as they were last spring. Visual Studio was flagging discrepancies, if there were any, between the files and the schema. It was quite happy with the above definitions.

**Comment by adrianholovaty** [comment]
I chatted about this with @mdgood and @dspreadbury yesterday, and here's a concrete proposal:

* Rename [`<directions> (global)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-global/) to `<attributes-global>`
* Rename [`<directions> (part)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-part/) to `<attributes>`
* Keep [`<directions> (sequence)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-sequence/) as `<directions>`
* Rename [`<measure> (global)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-global/) to `<measure-global>`
* Keep [`<measure> (part)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-part/) as `<measure>`

The philosophies here are:

* The bulk of an MNX document lives within parts and sequences, so we should use the nicer names (`<directions>` and `<measure>`) there.
* We tried to find a _different_ word, other than "direction," to refer to the measure-wide and part-wide information that lives in `<global>` and `<part>`. We arrived at "attributes", taken from MusicXML. It's not amazing, but...it does the job?

With these changes, we'll avoid any potential issues in schema validation, we'll avoid end-user confusion, and we'll be able to refer to the elements more precisely (less awkwardly) when developing the format.

Thoughts and suggestions welcome!

**Comment by cecilios** [comment]
> We arrived at "attributes", taken from MusicXML. It's not amazing, but...it does the job?

I'm used to MusicXML so to me it is a perfect name :). More seriously, `<directions> (part)` is just clef and key, and they are somehow attributes for the measure, so the name is sensible to me.

**Comment by joeberkovitz** [comment]
+1

**Comment by clnoel** [comment]
I was thinking `global-measure` instead of `measure-global`, but I guess yours works better alphabetically. I'm okay withthe part's directions (clef, key) becoming "attributes", but I have a harder time associating "repeat", "segno", and "fine" as "attributes". Those feel like directions to me (aside from the fact that I have to read `<fine/>` twice each time to pronounce it right in my head :P)

**Comment by adrianholovaty** [comment]
Yeah, `measure-global` is nicer alphabetically (it gets listed next to `measure`), and using `-global` as a suffix is somewhat similar to using `-layout` as a suffix. Just feels more consistent with the rest of our elements. :)

That's a good point about the global measure attributes feeling more like directions than attributes. So...`direction-measure`? Or something else?

**Comment by clnoel** [comment]
Hmm... I think `attributes-global` feels right here, but only for `key`, and `time` and for other measure "attributes" that we can specify (defaults for) at the global level (most of which haven't been defined yet). That leaves all the "jump" variations (repeats, endings, segno etc.) and tempo, all of which feel more like "directions". Can we do two children: `attributes-global` and `directions-global` ? Is that unnecessarily complicated?

**Comment by samuelbradshaw** [comment]
Is there any way we can consolidate global measures and part measures to simplify and avoid the issue altogether? Maybe by having `<part>` as a child of `<measure>` instead of the other way around, and `<part>`s having a reference attribute that ties the parts in each measure together?

```
<measure>
  <directions />
  <part ref="melody">
    <directions-part />
    ...
  </part>
  <part ref="harmony" />
</measure>
<measure>
  <directions />
  <part ref="melody" />
  <part ref="harmony" />
</measure>
```

**Comment by clnoel** [comment]
We went through that debate way back when (it's the MusicXML time-wise vs. part-wise debate), and we decided doing part-wise was a lot more understandable to more systems.

**Comment by ahankinson** [comment]
@clnoel is there an issue with the debate? I'd like to read it.

**Comment by clnoel** [comment]
@ahankinson The closest I can do is refer you to #2, which already assumed that there was "global" and several "parts". So, if there actually was the debate I remember, I don't think it was in an issue. It was either in-person, or maybe a mailing-list thread.

**Comment by cecilios** [comment]
In reference to @clnoel comments, https://github.com/w3c/mnx/issues/265#issuecomment-976942270 and https://github.com/w3c/mnx/issues/265#issuecomment-977070972 , I agree that for `<directions> (global)`, that contains many other directions, renaming it as `<attributes-global>` sounds rare. We could use `<directions-global>` instead, longer name but more coherent. So we will have

- `<directions> (global)` renamed as `<directions-global>`
- `<directions> (sequence)` kept as `<directions>`
- `<directions> (part)` renamed as `<attributes>`

And, at this point, I'm changing my mind and **would vote for homogeneity**. `<attributes>` is only clef and key, but for homogeneity, I think it will be better to rename `<directions> (part)` as `<directions-part>` instead of `<attributes>`.  Names are generated and consumed by computers and so it doesnt matter if they are a little longer, but a clear mental scheme is better for reasoning and understanding, and using two names, `attributtes` and `directions`, for containers with the same function and sometimes with the same content (e.g. clef) is, perhaps, less clear.

**Comment by adrianholovaty** [comment]
Thanks @cecilios. That sounds good to me as well. So the full list of changes would be:

* Rename [`<directions> (global)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-global/) to `<directions-global>`
* Rename [`<directions> (part)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-part/) to `<directions-part>`
* Keep [`<directions> (sequence)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/directions-sequence/) as `<directions>`
* Rename [`<measure> (global)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-global/) to `<measure-global>`
* Keep [`<measure> (part)`](https://w3c.github.io/mnx/docs/mnx-reference/elements/measure-part/) as `<measure>`

Any further thoughts/objections?

**Comment by notator** [comment]
@adrianholovaty
Its okay by me.
_Technically_, I think the change is unnecessary (schemas allow the same name to be used in different contexts), but I agree that the new names might help to disambiguate the elements during discussions.

I think you could now go ahead and make the improvements you had in mind when kicking this issue off. Possibly they need discussing?

**Comment by adrianholovaty** [comment]
The deed is done. I've just made these changes in a662f706, including an update of all example documents.
