### ISSUE TITLE
Must <mnx> contain at least one <score> element?

### ISSUE THREAD

**Issue by notator** [w3c/mnx#270]
The [documentation for the `<mnx>` element](https://w3c.github.io/mnx/docs/mnx-reference/elements/mnx/) says that it can contain `<score>` zero or more times.

I think this should be changed: `<mnx>` must contain one or more `<score>` elements.

**Reason 1:**
The inclusion of a mandatory `<score>` element makes MNX a free, open-source replacement for all the proprietary formats currently used by the major CWMN music notation editors.

Feasibility: 
The [documentation for the `<score>` element](https://w3c.github.io/mnx/docs/mnx-reference/elements/score/) says:
> MNX documents are not required to contain a `<score>` element. If `<score>` isn't provided, the default rendering behaviour is to include all parts — in the same order in which the `<part>` elements appear in the document — with line breaks and page breaks determined automatically by the consuming software.

I don't think there are any applications that can create `<part>` elements without displaying them in two dimensions on a screen. All applications that create (1-dimensional) parts also create (2-dimensional) scores that can be saved. This includes
1. applications that create `<score>` elements containing explicit `<page>` and `<system>` elements (i.e. mandatory system breaks).
2. (web-)applications that can create `<score>` elements containing no mandatory system-breaks.

**Reason 2:**
This makes #252 easy to resolve: If all MNX documents contain at least one `<score>`, then the default score can be defined as the first `<score>` to be defined in the file.

**Comment by dspreadbury** [comment]
Your first reason is all well and good in theory, @notator, but in practice no existing mature music notation application is going to switch to using MNX as its native format. It's just not a practical thing to do. In any case MNX would in no way be sufficient to serve as Dorico's native format, for example – and that's fine. Replacing the native file formats of existing music notation applications is not a goal for MNX. Given that this is a non-goal, I don't think any weight can or should be given to your Reason 1.

**Comment by notator** [comment]
> Replacing the native file formats of existing music notation applications is not a goal for MNX. 

What do you think MNX's goal is?

**Comment by dspreadbury** [comment]
MNX's goal is to meet the [use cases](https://w3c.github.io/mnx/use-cases/) we identified at the outset of the development process.

I don't believe we ever contemplated making one of the goals of the new standard that it should replace the file formats already in use by existing, mature music notation applications, because that is not a goal that would ever be likely to be achieved. No company with a large existing investment in their own file format (not only in time and development effort, but in terms of large numbers of users with tens or hundreds of thousands, or even millions, of existing files in that format) is realistically going to move to another format, however good it may be.

And, as I say, MNX wouldn't be a good match for our application as a native format, but I don't see this as an impediment at all. We have our existing native format, which we're free to extend and change as we see fit to meet the needs of our product development plans and our users, and we can implement support for MNX to support interchange and the other use cases identified by the group, which perhaps are not so well-served by our native format, which did not and does not have the goal of supporting all of those use cases.

**Comment by notator** [comment]
Okay. Its not essential to my argument that MNX should be used as Dorico's _internal_ format (though that could happen in the long term, as MNX matures).
MNX is initially intended to be a free, open source format that describes (both paper and web-based) scores. This
- covers the original use cases
- makes interchange formats like MusicXML redundant
- means that `<mnx>` must contain at least one `<score>` element.

**Comment by adrianholovaty** [comment]
This point has been rehashed in several Github comments (see [here](https://github.com/w3c/mnx/issues/252#issuecomment-972906110), [here](https://github.com/w3c/mnx/issues/252#issuecomment-973037851) and [here](https://github.com/w3c/mnx/issues/185#issuecomment-950291545), for example), but I'm glad you've opened an issue on this so that we can finally put it to rest in one convenient location.

There's still no good reason to require `<score>`. @notator, the reasons you gave above are very weak. Specific responses to your two reasons:

1. If an MNX document doesn't contain `<score>`, there's nothing preventing an application from using the notation data to determine its own line and page breaks.

2. It's true that requiring `<score>` would make it easier to decide which is the default rendering — but that's not strong enough of an argument to _require_ `<score>`.

As stated in various comments, applications that don't deal with specific renderings (such as DAWs or systems in which notation is dynamically laid out based on device), should _not_ be required to create dummy data simply for the purpose of checking the "fine, I've included a `<score>`" box. At best, this is irritating and error-prone, and at worst this would create a situation where these types of applications would create incorrect/dummy data ([see comment here](https://github.com/w3c/mnx/issues/185#issuecomment-950291545)).

Finally, I have not come across a single comment in favor of this idea from anybody other than @notator. This idea lacks broad support, or _any_ non-James-Ingram support.
