### ISSUE TITLE
Use SVG attributes to label graphic elements as notations

### ISSUE THREAD

**Issue by notator** [w3c/mnx#28]
In issue #26, @joeberkovitz  objected to the use of SVG `class` attributes in GMNX, saying (about GMNX as defined in the current proposals document):

> This allows GMNX to endow an SVG element with musical meaning, but without overloading the class attribute. Use of class or anything like it will wind up forcing the SVG element tree to conform to the structure of a notational element tree, which I feel is an unacceptable constraint on music rendering.

The SVG outlined in issue #25 declares standard score types that have associated standard element class names. There are only a few score types that will need to be defined, and I can only see advantages to using standard class names for standard element types. This is what SVG class attributes were designed for.

A client performing application may, for example, want to display stafflines in a special way when the staff is disabled. How else is the app going to know which elements are staves, and which are stafflines?
A notational element tree would be defined as part of the score type, and enable the score to be parsed efficiently to create the data structure that the consuming application needs.
This boils down to defining the use cases for the SVG file. I'm thinking an MNX SVG score should allow applications to interact with its elements at a fairly low level (to be defined).

I should add that I'm not the only one wanting to use SVG class attributes to describe element types in music scores. Verovio does too.

**Comment by joeberkovitz** [comment]
If SVG is tied to a separate semantic document via Id references, as proposed, there is no need to hijack SVG ideas like `class` to create "efficient data structures" -- because the data structures are already encoded efficiently, in a different document with its own structure, optimized for that purpose. SVG elements can use a pointer to elements in this other document to show what they represent. Using `class` attempts to force SVG, designed as an excellent solution to vector graphics, to simultaneously try to represent the structures of music notation.

So I do see disadvantages to using class names in the way you suggest. SVG classes, like HTML classes, were designed for application of visual styling. Using them as labels for notational elements goes beyond their design purpose, and tries to make one hierarchy do double duty for both.

The example supplied in #26 makes this clear: using SVG classes for tuplets, for example, forces the tuplet graphic to contain (in an XML sense) the note graphics of which it is made. But there is no innate reason that a notation renderer should produce such a structure, and in fact tuplet numbers and brackets don't really "contain" their notes in any graphical sense. So I think you need to explain how you will solve this problem of conflicting hierarchies, rather than just say that you see no downside to classes. (The fact that Verovio uses them is not really relevant -- we're defining a standard that will affect all renderings of all music, and Verovio is just one application doing what works for them.)

Finally, I also do not see how we can say that "there are only a few score types that will need to be defined". That is implicitly an ethnocentric statement. If we're truly interested in accommodating the notational systems of the world, including those we haven't thought of yet, then the graphical piece of GMNX needs to be free of all notational baggage.

**Comment by notator** [comment]
> SVG classes, like HTML classes, were designed for application of visual styling. 

Using SVG class attributes for visual styling in no way prevents them being used by client apps to usefully identify element types. For example: if the score type CWMN1950 is defined to include lines having class="staffline", then these lines can both be given a default CSS style and be identified as stafflines by the client software (which can then change the visual appearance as necessary at runtime).

The argument that SVG classes are intended for visual styling cuts the other way: Forcing the class information to be stored in a separate file actually _prevents_ the use of CSS in the SVG. Or, put another way, if classes are used for CSS purposes in the SVG, then there is no need to reference an external file to find the same information.

My own performable SVG scores ought to use CSS styling, but this is not currently the case. As Jeremy Sawruck said (on public-music-notation-contrib@w3.org ) "Good software engineering practice is to separate semantics from presentation".
Part of the problem is that styling SVG with CSS seems to be rather patchily implemented across the standard browsers: This [Mozzilla tutorial example](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS) currently works in Firefox but not in Chrome (12. 05.2017). 
For ease of viewing in both browsers, I've uploaded the example's realization to:
[http://james-ingram.de/tests/ChromeCSSBug/flower.svg](http://james-ingram.de/tests/ChromeCSSBug/flower.svg)
(This problem is well documented on the web...)

So there are currently two proposals on the table about the structure of GMNX scores (Issue #25), and maybe we will just have to agree to disagree.

Whichever strategy is chosen, successful adoption of a standard for GMNX will depend on its acceptance by the programmers who currently export SVG from their applications. So we really need input from that direction to solve any deadlock.

...

Tuplet brackets:
> The example supplied in #26 makes this clear: using SVG classes for tuplets, for example, forces the tuplet graphic to contain (in an XML sense) the note graphics of which it is made. But there is no innate reason that a notation renderer should produce such a structure, and in fact tuplet numbers and brackets don't really "contain" their notes in any graphical sense. So I think you need to explain how you will solve this problem of conflicting hierarchies, rather than just say that you see no downside to classes.

Contrary to the currently proposed situation in CWMNX, I am proposing that the durations of event symbols are supplied independently of the graphics in GMNX. This means that tuplet brackets can be treated as annotations in a CWMN GMNX score. Tuplet brackets would (like beams) have a defined place in the container hierarchy, but they are not themselves containers.

...

The world's music notations: 
> Finally, I also do not see how we can say that "there are only a few score types that will need to be defined". That is implicitly an ethnocentric statement. If we're truly interested in accommodating the notational systems of the world, including those we haven't thought of yet, then the graphical piece of GMNX needs to be free of all notational baggage.

I'll file a new issue about that.

**Comment by joeberkovitz** [comment]
I've retitled this issue for clarity. Note that `class` is not the only attribute that can be used to supply such a label.

**Comment by adrianholovaty** [comment]
(Closing this issue because MNX-Generic is no longer in scope for our community group.)
