### ISSUE TITLE
Changing <note> "accidental" attribute to remove redundancy

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#288]
At the moment, the `<note>` element's `accidental` attribute is used for two purposes:

* Its presence indicates that the accidental should be rendered.
* Its value indicates the specific accidental to use.

```xml
<note pitch="G#4" accidental="sharp"/>
```

See the [Accidentals example document](https://w3c.github.io/mnx/docs/mnx-reference/examples/accidentals/).

There are a few problems with this approach, though:

* It's redundant, because the specific accidental is encoded in both `pitch` and `accidental`.
* It enables nonsensical/undefined behavior like this:

```xml
<note pitch="C4" accidental="sharp"/>
```

* The name `accidental` is too vague. Somebody unfamiliar with MNX's details could easily misinterpret this as "the pitch's accidental" as opposed to "the rendered accidental."

I brought up these issues with the other co-chairs in our meeting yesterday, and all agreed we should change this (@mdgood, @dspreadbury, @mscuthbert). Here's a proposal:

1. Rename `accidental` to `rendered-accidental`. This is a more precise, and hopefully less confusing, name that more clearly communicates the point of it.

2. Change the allowed values from describing the glyph ("sharp", "flat", "natural") to describing the absence/presence and semantics. Valid values would be:

* `yes` — this accidental should be rendered
* `no` — (the default value) this accidental should explicitly _not_ be rendered
* `cautionary` — this accidental should be rendered, and by default it should use parentheses
* `editorial` — this accidental should be rendered, and by default it should use square brackets

For `cautionary` and `editorial`, the MNX styles system could provide [a selector](https://w3c.github.io/mnx/docs/mnx-reference/examples/style-element-basic/) to say "all `cautionary` accidentals should use a certain style."

One loose end I'd like to point out is regarding cautionary accidentals. Depending on your definition of "cautionary," there are actually two types of cautionary accidentals:

1. An accidental that is not strictly necessary but is used as a "heads-up" to the performer. It's rendered as a normal accidental, i.e., without parentheses or square brackets, so there's no visual difference between it and a non-cautionary accidental.
2. Same as 1, but with parentheses.

This can be considered a presentational decision, but some music software (including my own, Soundslice) has two separate concepts — a single score can contain both types of cautionary accidentals and it's not a global display preference.

I'm leaning toward encoding case 1 as `yes`, and case 2 as `cautionary`. But this is slightly inelegant, because both are technically cautionary and it's really just a visual difference. An alternative could be to have two options: `cautionary-noparens` and `cautionary-parens`.

Thoughts on all of this? Once we have some consensus, I can put together a pull request with the appropriate changes to docs and examples.

**Comment by mscuthbert** [comment]
There's one issue that's come up a couple of times in musicxml that this might be the time to address:  sometimes the editorial accidental is different from a notated accidental.  (For instance, a number of composers up to 1800 would write flat to cancel out a sharp to natural), so the note would have a flat accidental and an editorial natural accidental.  (This also happens with transcriptions of medieval music a lot with "ficta"; where the music is old but the transcription is CWN).  So I wonder if we want to make it something like:

"accidental-rendered" = yes / no  (default... no? yes?  no for natural, yes for all others?)
"accidental-editorial" = yes / no  (could later be expanded to deal with use cases above)
"accidental-cautionary" = yes / no (no need for later expansion)

Should we distinguish between accidental forced to render by override vs accidental rendered because that's what the renderer determines is best in context?  In music21 we have `Accidental.displayType` as an enum of "normal, always, never, if-absolutely-necessary, unless-repeated, even-tied" and `Accidental.displayStatus` which is True, False, unknown.  Where displayType represents the user's preference for display (normal is the default and means, look at the content and determine if it should be displayed).  `displayStatus` says "draw the sucker [or not]" with unknown as a placeholder for "we haven't determined if this accidental should be displayed yet or not" -- might not be needed for an interchange format but very valuable for an internal data format.

It seems that saving the user's wishes for the accidental is important in case notes are edited around it.  Finale's internal data format preserves my preferences on this, but they're lost on round-tripping in MusicXML.  Would be good to not have that happen in MNX.

**Comment by adrianholovaty** [comment]
This has been taken care of in 89d4541396, via the new `accidentalDisplay` key.
