### ISSUE TITLE
Barline object type ambiguity

### ISSUE THREAD

**Issue by GeorgeTailor** [w3c/mnx#326]
Hello,

[Global measure docs](https://w3c.github.io/mnx/docs/mnx-reference/objects/measure-global/) mention that one of the possible children is `barline`, which is marked as optional, however there are instructions on how to draw barline when it is not present in the spec. 

When we go to [barline docs](https://w3c.github.io/mnx/docs/mnx-reference/objects/barline/) it also mentiones that type is optional, which does not make any sense, since:
1.  it's the only property of this object
2. as mentioned in `global measure docs` it's either `light-heavy` or `regular`

IMO, specification is not a good place for logic, it should provide structure, otherwise we will end up with same problems as with MusicXML. I propose to mark `barline` as required in `global measure` object, also mark `type` of the barline object as required as well.

**Comment by adrianholovaty** [comment]
Thanks for the report — nicely spotted! Based on your comments, I think we need to change the following:

* Make "type" required for the [barline object](https://w3c.github.io/mnx/docs/mnx-reference/objects/barline/).
* Change the docs for the "barline" key in [measure global](https://w3c.github.io/mnx/docs/mnx-reference/objects/measure-global/) to unambiguously refer to the barline object's _type_. For example, "If the measure is the last in the document, use `{"type": "light-heavy"}`."
* Document all allowed values for [barline type](https://w3c.github.io/mnx/docs/mnx-reference/objects/barline-type/). This wasn't previously done because we didn't have a way to properly document enums, but that's now possible due to a recent improvement to our docs system.
