### ISSUE TITLE
The relation between CWMNX and GMNX

### ISSUE THREAD

**Issue by notator** [w3c/mnx#36]
If a standardized dialect of GMNX exists that describes instantiations of the scores described (abstractly) by a MusicXML file, then
1. It would be a good idea for its object class names and container structure to resemble MusicXML's, as far as possible.
2. Applications could read the GMNX file, ignore the instantiation data, and create their own instantiation.

Does this mean that CWMNX is a dialect of GMNX?

**Comment by joeberkovitz** [comment]
GMNX does not have notational dialects. It is a purely graphical and audio description of a score's instantiation. As such, its container structure need not necessarily correspond to any form of notation, and we don't intend to require this even for CWMN scores.  Applications are not allowed to ignore an instantiation of a GMNX document, because it is itself an instantiation.

However, if a GMNX score is a rendering of a score with a semantic document (e.g. a CWMNX score), it will allow _references_ embedded in the GMNX file, which point back to elements in that semantic document. This provides a way to optionally correlate elements in the GMNX with the CWMN constructs from which they were derived.

**Comment by notator** [comment]
I'm not sure if you have understood what I meant.

By "dialect" I mean the way the GMNX file is constructed. There would be information at the top of the file telling the parser how to parse the file. In other words, how its containers nest, the object class names it contains etc. There would one such "dialect" for CWMN files (created from MusicXML or CWMNX), and other dialects for Asian notations, ordinary text etc. I can't see how GMNX can be made to work without such specializations.

Am I right in thinking that CWMNX is going to have container structures and object class names very like those of MusicXML?

If so, an instantiation of a score that is originally described by CWMNX could very easily, have containers and element class names inherited from the CWMNX.
If an instantiation (GMNX file) does have such containers and element class names, then the application reading it could ignore the instantiation data, and either re-export a CWMNX file or provide instantiation data of its own.

Is there a detailed description of CWMNX somewhere? I need to take a close look at its containers and element classes. It would be great if the progress you are making with CWMNX could be reflected in the definition of the GMNX CWMN dialect.

The question is whether we really need _references_ (IDs) between two files, when we could simply go for mirroring. Parsing would be considerably simplified if there was only one file to parse.

**Comment by joeberkovitz** [comment]
There is no information telling a GMNX parser how to parse the file, because its parsing is very simple and is independent of whatever notational system is being used.

As such there is no such thing as a "GMNX CWMN dialect". We do not intend to package graphical instantiations and semantic descriptions in a single document format, and the charter reflects this decision. Hence the use of references.

This issue is closed.

**Comment by notator** [comment]
We are talking about two different proposals for GMNX.
Yours is outlined in the [MNX Proposal Overview](https://w3c.github.io/mnx/overview/), mine is outlined in issue #25.

Neither of these proposals is mentioned in the [Revised Group Charter](https://www.w3.org/community/music-notation/wiki/Revised_Group_Charter) that has recently been adopted.
The charter says that we are allowed to discuss proposals for both CWMNX and GMNX, but _nothing_ about their implementation details. In particular, there is nothing in the charter to say that GMNX has to use references in the way described in your proposal.

This issue is _not_, therefore, off limits as far as the charter is concerned, and I would like to ask for it to be re-opened.

**Comment by joeberkovitz** [comment]
What's off topic is the idea that GMNX contains object names that have semantic significance. That's what the charter speaks to: GMNX is not a semantic format.

#25 continues to track the references-vs-embedding issue.

**Comment by notator** [comment]
I don't see anything about GMNX's format in the charter.
But no matter. I'll continue this issue in #25.
