### ISSUE TITLE
Lack of support for ABC Notation / Re-inventing the wheel

### ISSUE THREAD

**Issue by leesavide** [w3c/mnx#44]
Not to put a damper on a good idea, but...

Web-based music notation already exists. Please see <https://abcnotation.com/>.  Also, see a working implementation of ABC music notation to SVG transformation via JavaScript here: <http://moinejf.free.fr/abcm2ps-doc/au_clair.xhtml>, which also plays the tune when clicked.

MusicXML and any derivatives from it have the downside of treating music notation as a document format, when they ought to treat it as a formal language with grammar and syntax. This allows new users to learn music notation while reading the language & using it in score writing applications. ABC notation does that, and has been doing that, since 1991.

**Comment by joeberkovitz** [comment]
Thanks -- we're well aware of both ABC notation, and also of other web-based approaches transforming notation markup into SVG (notably www.verovio.com).

We're continuing to work on MNX not because web-based notation doesn't exist, but because it doesn't serve enough of our use cases, which have been documented here: https://w3c.github.io/mnx/use-cases/

Both MusicXML and MNX impose a document grammar, but I would say that any digital encoding of conventional music notation that can address the full complexity of the canon, will not be the best way to help users learn notation. ABC will still have its place in the world as a simple way to notate simple scores by hand.

I suggest you keep following this project and consider ways that ABC notation can fit into it, understanding that we neither aim to replace ABC, nor do we regard the wheel we're working on as "already invented" :-)

**Comment by bwl21** [comment]
@leesavide raises valid arguments and you should not put them aside too fast. Reading the use cases, it is hard to find out which cases are not covered by at least music xml. In particular the use cases MC* and MT* are basically to be covered by music editing software and not that much by the underlying persistence format. In particular MC* is covered well by ABC-Notation.

Use cases RLP* also need to be covered by Software and require an approach where the particular extracts and formats are specified in configuration of the rendering tool. An ordinary musician will not be able to hack appropriate CSS  - Files and filters. No musician will edit MNX (or MusicXML files manually in a plain text editor).

In order to derive MNX from the use cases, a set of features should be derived from the use cases, which eventually are broken down to requirements. MNX then should refer to these requirements. This provides a proper requirements tracing. Presumably it will also reveal that it would be better to rather strengthen MusicXML than inventing something really new.

It appears to be an interesting idea to use a kind of css approach for the visual representation. Couldn't this be done on top of musicXML.

When defining such a standard the core issue is the model, not the model serialization. Such models should be represented in UML. This would allow various serialization approaches such as XML, JSON, YAML, ecore and so on. And it would help to understand the structure and to apply semantic constraints on the model level. It also would allow to create well defined subsets matching for particular usage scenarios.

In general, ABC is around for since 1991, pretty successful. And it is really possible to be used by persons with not much computer knowledge. I am utilizing ABC in [Zupfnoter](https://www.zupfnoter.de). This application is successfully used by persons even above the age of 70. Zupfnoter creates a music sheets for table harps, a niche in music which will not be covered by any standard. There is not even a need for that. But it is an application which is basically handles use cases MC* RLP*. For RLP* it uses a specific configuration which is represented in JSON and simply added to the ABC file.

MusicXML is covered by many popular music applications such as Editors, scanners etc.. In order to achieve the MNX objectives for the musicians, it is necessary to gain similar support by many music applications. This will be a long and windy road, maybe it will not happen!

**Comment by joeberkovitz** [comment]
@bwl21 A couple of points... 

- No one's setting aside the argument that ABC has value as a simple human-readable-writable format. But for the work of this group, the chair would prefer to see issues that propose _specific ways_ that ABC can be part of the proposed standard. This one, rather, asserted that the chair appeared not to know about ABC and -- I think -- implied that the CG should just adopt ABC overall and avoid wasting time reinventing the wheel. I think the group needs a more actionable and more thought-out proposal that explains the problems that ABC solves relative to MNX/MusicXML, and we can compare solutions to those problems.

- Yes, the challenge is indeed to create a model that serves the use cases. The current use case document is cross-referenced to the early MNX proposal, and will eventually be cross-referenced with the spec.

- I have put in years of working with UML models. As a result I don't love the idea of embracing UML wholesale, but I do think the spec can define a "serialization-agnostic" model that is philosophically similar: one that can support XML, JSON, etc. as you suggest. I would not want to do anything that would preclude that approach, and I'm sure others have feelings on the subject that should be heard. I'd suggest you open a separate issue on that rather than folding it into this one.
