### ISSUE TITLE
Ordering of grace notes relative to other notation

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#45]
CWMNX needs to allow scores to encode the notational ordering of grace notes relative to other objects. Such an ordering is well defined for non-grace notes, but there are particular problems with grace notes.

As a somewhat artificial scenario, consider this case:
- A staff in some measure contains two separate voices
- Voice 1 starts with a run of 4 grace notes (acciacatura), followed by a normal note
- Voice 2 starts with a run of 4 grace notes, followed by a normal note
- A change from F clef to G clef occurs just after grace note 1 of Voice 1, and just after grace note 2 of Voice 2. In other words, the F clef applies to the first grace note of Voice 1, and to the first two grace notes of Voice 2.
- Only a single G clef appears: there's no switching back and forth between F and G.

Questions:
-  is the clef change specified at measure level (once), or at voice level (twice)?
- if at measure level, how is its effect on the grace notes known?

**Comment by clnoel** [comment]
Here is a _real example_ of a piece that came into us (Musicnotes) recently, that completely and utterly failed somewhere in the Sibelius MusicXML export and our MusicXML import. We ended up with the clef change before all the grace notes, and the octava applying only to the regular note the grace notes are attached to. I would like to make sure that MNX has a well-defined way to do this.

![image](https://user-images.githubusercontent.com/6453511/152571539-c4db4b7e-d89e-47c7-8e68-9b80539fa0de.png)


As I note that the `<grace>` element currently does not allow directions at all, even though it looks like it's supposed to based on its explanatory text, I thought I would add this example into the mix.

**Comment by mdgood** [comment]
@clnoel This is likely a deficiency in the MusicXML export rather than in MusicXML. Directions can be placed before and after grace notes just like they can with regular notes. The problem for our plug-in is likely that all these events are represented to the plug-in at the same musical time, so you can't tell where the `<octave-shift>` should appear in the MusicXML output. I'm not sure why native export would have the same issue, but perhaps it's related.

If you email me the original Sibelius file I can take a look. I'm also not sure why the clef change would be a problem in this example. We just released a new version of the Dolet for Sibelius plug-in, so maybe there are things to fix in a maintenance update. Perhaps there is even some additional information we can use for the `<octave-shift>` that we overlooked before.

**Comment by clnoel** [comment]
@mdgood Thanks! I'll be communicating with you about that outside this issue. I still feel like making sure that that example works in a _defined way_ for MNX is important.

**Comment by adrianholovaty** [comment]
Closing this in favor of #313.
