### ISSUE TITLE
The <space> event is awkward

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#5]
It may be cleaner to specify spaces, if they are adopted, as empty `<event>` elements. This has an advantage in that it simplifies the schema, and gives meaning to a structure that can arise naturally in the course of manipulating an MNX DOM when the content of an event is removed.

**Comment by joeberkovitz** [comment]
Note that spaces differ from regular events in at least one crucial way: their duration is not constrained to CMN note values (since a space is neither a note nor rest). Consider a 4/4 measure consisting of an eighth note at the beginning, and a quarter note at the end, and space in between. The duration of the space is 5/8, which is not expressible as a standard note value in CMN.

This perhaps argues for spaces to have their own identity as an MNX element, since their durational constraints are distinct from events. However, it doesn't mean that an empty `<event>` doesn't have a valid interpretation.

**Comment by siennamw** [comment]
From your description, it sounds like spaces _are_ constrained to CMN note values, but that their durations can be composite (from your example, a 5/8 duration can be easily expressed as a half note plus an eighth note, 5 eighth notes, or in many other ways...).  This seems logical to me.

I'm not sure I understand why a `<space>` element is necessary, however.  Why not use an empty `<event>` element, or something like `<event type='space'>`?

**Comment by joeberkovitz** [comment]
@siennamw The purpose of a space is to advance the time cursor that determines the position of the next element in the sequence. As long as the next element winds up at a position that is legal in a CMN sense, there is no limitation on the duration of the space. So 5/8 is perfectly OK as a space duration (assuming it doesn't take one past the end of the measure).

Empty events would work just fine, were it not for the fact that we're taking pains (at least for now) to constrain their durations to legal CMN note values, to prevent non-CMN constructs from being encoded.  We could lift that constraint for empty events only, but that would allow inconsistent behavior during the lifecycle of an `<event>` (recalling that we do want to allow live manipulation of these structures in code). Imagine making an empty event of duration 5/8 (ok), then putting a note inside it (suddenly, not ok).

Anyway, I'm not advocating any specific position on this yet, just exposing the issue for the community to consider!

**Comment by siennamw** [comment]
Seems like a space element should be self-closing, `<space />` instead of `<space></space>`, because should not contain anything.  This combined with the different constraints on duration does seem to justify an independent element.

**Comment by cecilios** [comment]
The only need I see for the `space` element is when several voices are represented in the same staff (i.e. a piano score) [incidentally, are there any other uses I am not aware?]. In these cases it is normal in some cases not to write rests for secondary voices. As the MNX draft says "in MusicXML, these gaps were often created using the forward and backward elements or with hidden rests".

I never liked the procedural `forward` and `backward` MusicXML elements so in my software I arrived to the same solution proposed here, an `space` element constrained to: 
	- use a metrical time interval,
	- the implied time position must not be grater that end of current measure, and
	- must be associated to a voice.

My thoughts:
- In the MNX proposal, the <space> is not constrained to a voice. Is this make sense? I think that it must be constrained.
- The `space` can be considered as a kind of empty event, but as said, its duration is not only legal note durations but metrical time intervals. If `space` is not used, then a new type of event should be created and the duration constrain has to be relaxed for these empty events. Also, other sub-elements of `event` should be forbidden. So I think its is simpler and more practical to maintain the `space` instead of creating a new type of event.
- Is there a constrain forcing that the implied final time position must not be grater that end of current measure? Should this constrain be created?
- Finally, the tag name `space` has layout related connotations. I would suggest changing the tag name to other, such as `voiceGap`, `gap` or  `goFwd`.

**Comment by joeberkovitz** [comment]
We wound up changing the name of this element to `<forward>` for all the reasons summarized above. Please see https://w3c.github.io/mnx/specification/#the-forward-element

We still permit empty `<event>` elements at the moment. These are effectively the same as `<forward>` but they are less flexible, since an event can't assume the duration of, say, 5 eighth notes, but you can have `<forward duration="5/8"/>`.

**Comment by joeberkovitz** [comment]
We think this can be closed now -- putting into Active Review to highlight it.
