### ISSUE TITLE
How should directions be positioned metrically?

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#6]
Directions may...

- belong to a specific sequence or voice
- overlap events within the sequence that they belong to
- occur at any metrical position within a measure

Therefore we need a way to position directions that do not share the same metrical position as an `<event>` element. (The event cursor provides support for these already.)

Some proposals include:

1. adjust directions using some arbitrary temporal offset from the cursor, expressed in a ticks-like unit (similar to MusicXML's `offset` attribute -- something like `offset="-480"`). This offset would not be allowed to move a direction outside the measure, or to result in out-of-order elements the parent `<sequence>`.

1. specify an explicit measure-relative position for directions in metrical units (e.g. `position="2/4"`). It would not be permitted to have out-of-order elements in the parent `<sequence>`.

1. adjust directions, but allow non-ticks units (e.g. `offset="-2/4"`).

**Comment by Webern** [comment]
Strongly in favor of option #2.  Thanks!

**Comment by siennamw** [comment]
I also support option 2.

**Comment by joeberkovitz** [comment]
I have no quarrel with option 2 (my personal preference) but I would love it if @Webern @siennamw (and others) could provide some more background on why they prefer whatever option they're backing.

For what it's worth, my reasoning is: There's no computational reason to prefer any of these approaches, it's all about human comprehension. Now, this case applies only to directions that are not temporally aligned with a note-value element. Given that assumption, using "offset" is somewhat less clear than "position" because it forces the human reader to do a calculation in their head relative to some other element.

**Comment by Webern** [comment]
@joeberkovitz I do find a computational reason to prefer option 2 over option 1.  In general the more that the data in the document can be "stateless" the better.  It puts less burden on the computational implementation to maintain a "current state" while reading the document and allows to program to process the directions whenever is convenient.

With option 1 we have a state machine (I usually call this the "stack") that must be referenced when we encounter a direction.  With option 2 the direction contains all the information necessary and the the surrounding state has less influence on it.  For me, I find the latter easier to implement.

As for option 3.  Personally I wish ticks would go away.  In my opinion they have nothing to do with visual or semantic representation of music.  As you know, I'm a purist, I would prefer not to have performance information in the document either (which is where ticks might become necessary), but that's just me.  To me, ticks seems like a pollution of music encoding due to the quantum nature of the way we implement stuff in the computer.  No composer says, "I am going to define a tick to mean 1/100th of a quarter note.  And see this Forte mark here, I want it to happen 223 ticks into the measure."

**Comment by Webern** [comment]
p.s. For option 2 I also prefer to have directions separated from the events in an entirely different element.  One thing I dislike about parsing MusicXML is that basically anything can happen anywhere.  The events are not inside of their own events element, the measure attributes are not inside of their own measure attributes element.

also, I think that when I read your original post I was assuming that these directions could/would be in their own element instead of interspersed throughout the event stream.  I would prefer to see the directions in an entirely different element from the events.  In the case that a direction is "attached" to a note, an ID pointer would be needed.  But that's probably not what you had in mind.

**Comment by siennamw** [comment]
I agree with @Webern that

> ...I wish ticks would go away. In my opinion they have nothing to do with visual or semantic representation of music.

Ticks are an unmusical byproduct of encoding.  In my view they should be deprecated if not outright eliminated in CWMNX.

I also agree that positioning absolutely within the measure will be much easier to manage (both for people and machines) than positioning that relies on offsets.

**Comment by joeberkovitz** [comment]
Thanks everyone for the additional observations behind your choices -- this is very helpful.

@Webern in most cases, a direction is simultaneous with an event and there is no need for any special metrical positioning attributes. But... the idea of segregating directions is worth thinking about further. While in the normal case (directions simultaneous with events) this might feel like extra baggage, it does seem to result in a cleaner model at the expense of multiplying the number of distinct time-ordered sequences.

**Comment by Webern** [comment]
Maybe for simplicity directions could optionally be embedded within the event, where time positioning would be disallowed.  Or segregated where time positioning is required.  This would explicitly distinguish "note attached" marks from "measure attached" marks (to borrow Finale's terminology again.)

**Comment by joeberkovitz** [comment]
@Webern nice option to consider.

Additionally I'd observe that there are more options for "attachment" than just "note" and "measure" -- for example, directions may belong to a particular sequence/layer within the measure. Multiple voices in a polyphonic measure might carry their own dynamics, for example, or there might only be overall dynamics that apply to all voices.

I think that deserves another issue, so I've filed it: #32

**Comment by joeberkovitz** [comment]
Proposal from chair call today: 
- force all direction elements that are simultaneous with events to be placed _inside_ the event element (which gets rid of the ambiguity of putting simultaneous directions _before_ the event).
- require all other directions to carry an explicit metrical `position` attribute (i.e. option 2)
- keep the requirement that events and directions occur in monotonically increasing order within a sequence

**Comment by Webern** [comment]
These proposals sound great, thank you!


.mjb

**Comment by joeberkovitz** [comment]
This has now taken shape as described in https://w3c.github.io/mnx/specification/#cwmnx-direction-content

The main difference from the previous comment is that currently directions are not allowed _inside_ an `<event>`. This began to feel unnecessarily complicated, and we've instead adopted a `<directions>` element that groups all directions together under a measure or sequence that have explicit, absolute positions.

**Comment by joeberkovitz** [comment]
Note to reviewers: this has a significant relationship with issue #32 .

**Comment by cschardt** [comment]
I think we need an additional component, which contains a fixed distance of the symbol from the time position. So the resulting position would be x(time) + dx.
Example: imagine " < ff > ", i.e. a whole note with a hairpin longing to the ff at position 2/4 followed by the closing hairpin. The ff is linked to the central time of the note, but what about the hairpins? their open ends are placed in such a way, that they are close to the ff but do not touch it. The semantic description of their position would not be "at timpoint 0.8*2/4" but rather "at 2/4 moved 2 spaces to the left".
When the measure has large stretch differences in parts vs. full score, this is a potentially notable difference.

**Comment by joeberkovitz** [comment]
@cschardt I agree about the need here -- perhaps something analogous to MusicXML's `relative-x' attribute, but expressed as a style property (like https://w3c.github.io/mnx/specification/#the-y-property does for absolute vertical positioning) since it's about presentation and not semantics.

This has potentially some interaction with #13 and #15, so we may want to progress that thinking a bit more. Ideally, whatever we do for directions could also play a role for events.

**Comment by mscuthbert** [comment]
Rather late to the game and perhaps getting a "GO AWAY" note, but thinking through the issue and about a comment Joe made in the W3C video (something like "The crescendo is positioned with offset 8, 8 staff lines, I think, or tenths of a staff line...well, it's in the specs") I'm wondering if we should follow the lead of CSS and either allowing or requiring units for directions, such that while there might be a default for numeric data (8 = "8/10ths of the current staffline") we could have other units available.  Some of them could be immediately converted with a constant ("8tenths === 0.8lines"), some of which have contextual conversions ("22pt" = ?? tenths, but can be looked up), and some would be dependent on the mode of output (e.g., 14px; 3rem; 0.2cm), and some could fluctuate depending on the context (0.2beats).  Unlike current CSS measurement specs, I think that allowing an ordered list of measurements would be important so that different media can use different units:  "offset: 0.3cm | 2tenths"

**Comment by joeberkovitz** [comment]
@mscuthbert I agree that units should be permitted, much like `px` or `em` are permitted in CSS font sizes.  But I would suggest that flexibility with respect to units should be restricted to MNX style properties (since these are by definition presentation data), and that we keep the units used by a direction's `position` as musical time. 

In this way a direction can bear both a `position` attribute showing what musical time it is anchored to, and one or more style properties that specify additional positional adjustments in specified units.

With respect to mode of output, I an mot sure that it is practical to tie units to a specific output medium or device. We need another way restricting style decisions to particular modes of output; I've opened a new issue #70 to reflect this.

**Comment by joeberkovitz** [comment]
The co-chairs reviewed this issue today. We propose taking the following steps to resolve it:

- Unify the way directions are encoded, by always placing them in a [`<directions>`](https://w3c.github.io/mnx/specification/#the-directions-element) element and requiring an explicit temporal `location` attribute. For clarity and simplicity, we'd remove the present option of allowing directions to be interspersed with events within a `<sequence>` (_i.e._ delete the second bullet point under https://w3c.github.io/mnx/specification/#cwmnx-direction-content).

- Note that `<directions>` already solves the problem of distinguishing voice-specific directions from part-specific directions from score-wide global directions, according to its placement.

- Add a new `dx` style property that gives a positional offset for an object relative to its default position.  (Temporal offsets are not required for a style property, since they can simply contribute to the object's `location` attribute.) Note that this is similar to MusicXML's `relative-x` position, NOT `measure-x`. Discussion of the units employed should be moved to #7.
