### ISSUE TITLE
How to include a mid-measure barline?

### ISSUE THREAD

**Issue by cecilios** [w3c/mnx#61]
I'm wondering how to include a mid-measure barline, or a barline in unmeasured bars (no time signature music), or an explicit barline at the end of a `<measure>`.

From current spec. it is not clear if `<barline>` must be a child of `<directions>`, a child of `<sequence>` or what. Current spec. only allows barlines as child of `<directions>`, and directions only at start of measure.

**Comment by joeberkovitz** [comment]
@cecilios As per the current spec, barlines _other than at the end of the measure_ are a `<barline>` direction: https://w3c.github.io/mnx/specification/#the-barline-element

Side note: Directions may be placed at any point in the measure, including at the end. Putting a direction at the end of a `<sequence>` or assigning it a `position` attribute equal to the measure direction both accomplish this.

Since this was just a question and not an issue, closing -- please open a new issue if there is a problem with the current spec regarding barlines.
