### ISSUE TITLE
Register rationale for changes

### ISSUE THREAD

**Issue by cecilios** [w3c/mnx#62]
It would be of help if as the specification advances, the ideas and rationale for new elements or changes could be available and summarized somewere, perhaps in the specification, as a 'note' block that could be easily spotted and removed when convenient, or in an annex. Preserving the rationale information could be of great help. For instance, to have a better understanding when studying the specification; or when an issue arises and something should be revised, to facilitate this revision by having the hole picture in mind.

**Comment by joeberkovitz** [comment]
We certainly do need to capture rationales. Since all changes must have a corresponding issue in the repository going forward, we do expect the issue threads to carry much of the burden. Issues not only record the rationale for each change, but the discussion which preceded the change.  We also will require pull requests for every change, which ensures that commits are cross-referenced to the issues that they resolve.

Having said that, let's leave this open for further discussion. While the above issue/pull-request driven process is followed by other W3C groups and seems to work well as a means for recording what happened along the way, what else might we need in addition to that?  If we have a change log that references each issue, what value should it add?

**Comment by cecilios** [comment]
Certainly, you are right that the issues thread is valuable and, anyway,
I'm not referring to create any new log. I was thinking in including (at
least temporarily, while the draft is being analysed and discussed) small
notes in the draft document pointing to the relevant thread and recording,
as bullet points, the main relevant reasoning. For instance, I really lost
the reasoning that the <global> element was introduced for capturing score
constrains. A small note attached to each pertinent  element, summarizing
in two-three lines any relevant thought and pointing to the issues thread
would be very valuable. Not only for people following the discussions
(after some time, we might forget the reasons) but also for new people
wishing to evaluate the standard.

Anyway, this is just a though from someone with bad memory. Of course this
is non sense if recording these rationale bullet point, takes too much work.
Regards,

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
