### ISSUE TITLE
Time units of performance mapping should always be absolute

### ISSUE THREAD

**Issue by notator** [w3c/mnx#66]
Thanks for posting the video of the NAMM meeting.

Apropos the discussion of performance styling (Joe's introduction is at ca. 58' 10"- 59'27")
Nowadays, performers learn performance style by listening to recordings of real performances by real performers. They no longer listen to metronomes if such an instantiation is available.
This is true in all genres (jazz, opera, classical, popular etc.) Actually, its always been that way: the best way to learn how to play Chopin was always to learn from Chopin himself, or from someone who had studied with him. There are whole traditions of perfomance practice, and no absolutely correct way to play any score. Performance practice traditions are always stored in peoples minds, never in computer files.
So I think MNX needs to be able to synchronize a score with one or more default, temporal instantiations (Simple MIDI data will do, if there are no recordings available, but recordings of real performances are preferable. Either way, the demo performances do not have to be "metronomic").

**Comment by joeberkovitz** [comment]
GMNX already specifies a capability to synchronize a score with any number of either audio files or MIDI-equivalent data - please see https://w3c.github.io/mnx/specification/index.html#gmnx-performance

If this does not meet a use case that you have in mind, please provide a specific scenario and propose a concrete change to the specification that would result in the use case being addressed.

**Comment by notator** [comment]
The use case I have in mind is the cultivation of _Performance style_ traditions in relation to all kinds of music notation, including CWMN. I'm not just talking about GMNX.

In this respect, there are at least two things that bother me about the current draft specification:
1. Occam's Razor. We don't need to create a large new specification, if the same or more powerful results can be achieved by refining an existing standard. (i.e. the `<svg>` container tag is to be preferred over both `<cwmnx>` and `<gmnx>`)
2. Division of responsibility. (This also relates to the NAMM debate about the relative _spatial_ positioning of symbols by different applications.) Tempo is a parameter that should be dealt with by notation editors (especially CWMN editors) if their users want that capability. But tempo does not belong in a standard that has to be read by machines. Machines dont have tempo. They deal with durations simply in terms of seconds, milliseconds etc. (Note that tempo was left out of the Web MIDI API. The Web MIDI API just uses milliseconds.)

When exporting SVG, together with demo performances or recordings, applications should simply use absolute time units (seconds, milliseconds etc.) relative to the start of a performance, just as they use graphic coordinates relative to the page's x,y origin. 

The point I was trying to make when I opened this issue, is that performance style is a temporal phenomenon which can't be captured in machine-readable form, and so can't be  defined using something like CSS. Humans learn (traditions of) performance style by listening to real performances, and committing them to memory in some way. But human memory is far more complicated than machine-time (which is currently realized by counting the vibrations of some crystal). In fact, nobody knows how human memory works, and we should not try to pretend that we do.

So my criticism of 
[https://w3c.github.io/mnx/specification/index.html#gmnx-performance](https://w3c.github.io/mnx/specification/index.html#gmnx-performance)
is that it tries to define a performance style model, where that is _in principle_ impossible. The inclusion of audio (and/or maybe MIDI) files is all we can (or need to) do.

§6.1.3.1 of the draft spec says:
> The performance-audio element defines one or more audio media files that constitute a single performance of the score, and whose contents are presumed to be temporally synchronized with each other.

That's an unnecessary restriction. The audio files don't have to be temporally synchronized with each other. They ought, if supplied, to be synchronized with _the graphics_. I think a scheme like [my cursor proposal](https://github.com/w3c/mnx/issues/25#issuecomment-360415773) would be much easier to implement than the draft spec's `<performance-mapping>` model. It would also apply to _any_ music notation including CWMN. (See Occam's Razor above).

**Comment by joeberkovitz** [comment]
I'll bypass the points here that are already captured in your SVG proposal #25, since the chairs have asked you not to duplicate that issue, and it's going to be reviewed separately.

> But tempo does not belong in a standard that has to be read by machines. Machines dont have tempo. They deal with durations simply in terms of seconds, milliseconds etc. (Note that tempo was left out of the Web MIDI API. The Web MIDI API just uses milliseconds.)

An argument based on the fact that a machine is reading a file has no weight in the decision-making process of this group. Humans are using the machines in question, so issues must be defended in terms of how they serve human use cases, or don't serve them. One might as well argue that CSS should not support font sizes in points, because machines don't have "points". But people care about points, and so they're useful. 

People care about tempo too. The inclusion of optional tempo definitions serves a definite use case for graphic/audio synchronization, namely that an audio file can be mapped to the musical time units employed in a score, and many notational systems (not just CWMN) employ a time unit that is not equal to seconds.

Note that references to tempo can be avoided in GMNX by simply omitting any definition of it, in which case the units employed are seconds. So it is easy to cover the pure-time use case that you are interested in.

> That's an unnecessary restriction. The audio files don't have to be temporally synchronized with each other. 

Ah, I see that you misunderstood the spec here. Indeed, it's not clear enough and should be fixed.

Each `<performance-media>` element describes a completely separate audio performance, _and these performances do not have to be synchronized_. However, within a single audio performance, multiple tracks may be provided in separate files, and _these tracks must be synchronized_ (as tracks normally are).  I'll fix the language accordingly.

So far, it seems like we're covering the bases you want covered, and your statements about the inclusion of either audio media or MIDI-like data are addressed by GMNX as it stands. This is intentional: we share exactly the same goal here of allowing people to experience a score in relation to multiple performances, each of which has its own synchronization basis.

**Comment by notator** [comment]
Sorry, but I was a bit confused above. Joe was quite right to label this issue just with GMNX.
But there's still an important issue here that needs clearing up:

As the heir to MusicXML, CWMNX has client applications that all support tempo in one way or another, and, since it is highly non-trivial to calculate a tempo from a series of absolute durations, I have nothing against CWMNX exporting tempo information as proposed. However, I should stay out of the CWMNX debate.

GMNX, on the other hand, targets a much wider set of applications, and should, I think always export the absolute times of performed events re the start of the performance. Note, however, that the CWMN flavour of GMNX could contain a graphical object that has `class="tempoIndication"` from which an application could infer a default tempo that is different from the one that would be calculated from any real, absolute durations given in the file.

I still think that the `<gmnx>` tag can be replaced by an `<svg>` tag. It remains to be seen, whether the CWMN flavour of GMNX can be made powerful enough for `<svg>` to replace `<cwmnx>`.

**Comment by joeberkovitz** [comment]
The current GMNX proposal supports simple linear conversion of "notated time units" (i.e. taking a provided tempo into account)  into absolute time.  As previously noted, the tempo can be omitted if absolute units are desired, e.g. as in the Lutoslawski sample.

The concept of a notated time unit is not specific to CWMN, so I believe it has value as something to include in the GMNX proposal. Others, feel free to chime in on whether this feature adds value, or adds unnecessary implementation effort.

I'll retitle this issue to avoid further confusion.

**Comment by notator** [comment]
I think this issue applies to both MNX-Common and MNX-Generic (please change the labels).
Clarification: Following #132, I now think that all MNX durations (`duration` attributes etc.) should be expressed in whole-note units (as they currently are), but that timings in live performances, synchronisation with the playback of external files, and playback using the information in MNX files can only be done in "real time" using absolute units (seconds). The MNX duration values are converted to absolute values using a time modification ratio (=tuplets) and the current tempo.

**Comment by adrianholovaty** [comment]
(Closing this issue because MNX-Generic is no longer in scope for our community group.)
