### ISSUE TITLE
Refine the definitions of MNX-Common profiles

### ISSUE THREAD

**Issue by cecilios** [w3c/mnx#68]
I'm worried about accepting the 'standard' profile without more analysis.

When MNX was started it always was said that it intended to cover at least all standard Common Western Music Notation (CWMN). So I expected that it would cover at least the following score types:

- normal scores: Time signature is defined in all score parts since start. All time signatures are equal.

- measure-free (no metric) scores. No time signature, no measures, no barlines. E.g.:

![image](https://user-images.githubusercontent.com/5238679/36075971-382f0c1a-0f56-11e8-8644-39a1afcaea5e.png)

- snippet scores (i.e. scores for text books): Some have barlines but no time signature. No constrains on the content between bars (irregular measures). Very short scores. Usually only one score part. E.g.:

![image](https://user-images.githubusercontent.com/5238679/36075973-465c8c90-0f56-11e8-81ec-bf65ffba474c.png)

- multi-metric scores: Time signature in all score parts since start. Different time signature in some score parts. E.g.:

![image](https://user-images.githubusercontent.com/5238679/36075967-22cfff28-0f56-11e8-878f-38b8f70d2d97.png)

The current draft proposal is centered in the so called 'standard' profile. This profile practically restricts its use to what I've called 'normal scores' and suggests that for other types (e.g. multi-metric) other profiles should be created.

While I'm not opposite to accepting the 'standard' profile as it is now defined, and creating more profiles if necessary, I'm contrary to taking this decision without more considerations.

First and crucial, I think that before taking a decision it is necessary to analyse the proposal for supporting the three other score types. Without that information it is not possible to judge the merits or problems of the 'standard' profile, as well as to judge its convenience and suitability. Take into account that creating specific score profiles for each one of these score types could create practical artificial barriers for supporting them. 
 
Second, but not less important, the name 'standard' suggests that it covers standard CWMN, but that is not the case, as the other three score types are also standard CWMN. If, finally, this profile is maintained I would suggest to change its name to better reflect to what it refers, and to not dismiss the importance of all other standard CWMN scores and misguide people when they decide to support the MNX standard.

Finally, I observe that the global element has some redundancy with the score profile. For instance, the main restrictions imposed by the 'standard' profile can be simply achieved by defining time signatures and all measures in the global element, without the need that this be mandatory in the 'standard' profile. If this would not be mandatory, then the standard profile could probably deal with all the other score types, without loosing the gain of imposing restrictions to valid content.

**Comment by joeberkovitz** [comment]
These are all reasonable thoughts. While not speaking for the other co-chairs, I don't feel the need to accept the `standard` profile definition right now, since it depends on many other questions. It's probably best to let other core issues of representation be resolved first, then come back to this issue later when we have a better handle. It seems likely that the definition of `standard` could change as we solve those other problems.

Note that existing issue #55 covers the multi-metric question, and that what you call "snippet" scores are already covered by the `standard` profile.  Please create a new, more specific issue for how "measure-free" scores are represented. We can then keep #68 as a reminder to revisit the definition of `standard` later in the process.

**Comment by cecilios** [comment]
Ok, thank you. I will open specific issues.

**Comment by clnoel** [comment]
I disagree. Since the standard profile listing is already in the spec, listing things like insisting on the same number of measures per part, we shouldn't put off this discussion. We absolutely want to be able to represent music with no measures, no meter (and therefore no measures), and multiple-meters as part of MNX-Common, so we should decide very soon how the profile is going to interact with the decisions we're making in other places.

We might need other profiles, but from what I can see, multi-metric needs it's own profile. There are definitely programs out there that can't handle those scores and should know about it up front.

If we need a simple split that will split "standard" scores from "multi-metric" or perhaps some other divisions, perhaps our definition of standard should say that it can only include one global!

**Comment by joeberkovitz** [comment]
Building on @clnoel's suggestion (which is a good "starter kit" of constraints and corresponds to most of the non-`standard` practices already noted in the spec, although there are more edge cases that need to be disallowed)...

- Define each one of these "guarantees" as being a uniquely named "simple profile", with names like `single-meter`, `complete-measures`, `consistent-sequences`, etc.

- Define "compound profiles" as named aggregates of simple profiles. So something like `standard` would be a defined set of guarantees. To the extent that we agree on other such built-in compound profiles, we could define those too.

- Allow the `profile` attribute for a score to string together multiple guarantees.

- Endow the `standard` compound profile with a special status: only scores which support it (_i.e._ which support each of the simple profiles within it) can rely on exchange throughout the MNX-Common ecosystem. However, when scores do break this profile, we have a good mechanism for them to say exactly how they are breaking it (by being specific about the simple profiles that they support).

**Comment by cecilios** [comment]
I must insist on reconsidering the name 'standard'.

Although I agree that the profile currently named 'standard' must be acceptable by all MNX-Common consumer applications, it is just a 'basic' or 'core' profile and has nothing to do with any standard. 

As already said in other posts, the name 'standard' could miss-guide implementors on the assumption that by implementing the 'standard' profile they will cover all CWMN music.

'standard' is less meaningful and subject to more misunderstandings than other names such as 'core', basic' or 'common-minimal'.

**Comment by joeberkovitz** [comment]
Don't take any of my comments as meaning we should keep the name `standard`. I am sure we can find a better name. I'll retitle the issue so that this is better understood.

**Comment by cecilios** [comment]
@joeberkovitz Thanks

@clnoel
>    Has a meter: This meter can be hidden in display, but should exist in the encoding.
> This can represent snippets (with hidden meters), pieces with no measures (by ...

The semantic should be represented without hidden elements as the 'hidden' attribute is something related to visual layout. For scores without time signature it is a kind of trick to include a time signature!. It it is better to explicitly encode that no time signature is present and relay in some other alternative element for specifying the 'measure' or snippet duration.

In issue #69 I have written some of my concerns for snippet scores.

**Comment by clnoel** [comment]
@cecilios That's why I said that these guarantees made it possible to encode snippet scores, even if it wasn't the best way. It's exactly a "trick" or "hack," but so is playing with event durations on pieces in order to make them match the meter.

On the other hand, the point of requiring a time signature in this basic profile is exactly what you just implied: to give the consuming program a chance to know the duration of each measure, and therefore the whole piece, ahead of time. I think I'm ok with a time signature being just one of the ways we specify that.

**Comment by cecilios** [comment]
@clnoel  I'm only against having to use tricks / hacks and to distort the semantics without need. Having to determine if an score has time signature by looking at visual style is a bad solution. Hacks are sometimes the less bad solution when everything is designed and in place. But we are at the design phase and thus, we have time for finding better solutions.

If the score has barlines, the duration between two barlines should be implied by the contained events and it is not necessary to include a hidden time signature. But if it is a requirement to explicitly encode the duration of each measure, there are alternatives without using tricks. For instance, in current draft spec., if an score does not have a time signature, the `time` element should say that, and the measure duration will be given by the 'measure' attribute in the `time` element. The drawback for snippet scores such as the one in the example in a previous post is that it is necessary to change the time signature on each _"measure"_. It would be better a solution not requiring the `time` element as mandatory: if it is not present just require a 'duration' attribute on each `measure` element.

**Comment by clnoel** [comment]
@cecilios I think I see the issue here. The meter of a piece is not a visual style, and I do not consider the <time> element to be a visual style, but rather to have the semantic meaning of defining the meter, whether it displays or not. Yes, in cases where the duration of the measures changes every measure, you would need a time element every measure in my proposed version of the core/basic/well-behaved profile. This is so that a scan of the <global> element is enough to set up all the measures. It also helps reinforce having the same meter in all parts, and having the measure sequences fill the meter.

The current spec does not have a duration attribute attached to the <measure> element. I'm guessing you are proposing adding one, as a way of overriding the current meter set by the <time> element for one measure, or for supplying duration when there is no <time> element. I think I'm against that because the <time> element seems to already cover those cases. It just needs to have no display aspect sometimes.

**Comment by cecilios** [comment]
@clnoel 
> It just needs to have no display aspect sometimes.

No, it needs a `signature="none"` value. Display aspects are visual style properties, not semantic values.

> you would need a time element every measure in my proposed version of the core/basic/well-behaved profile. This is so that a scan of the global element is enough to set up all the measures. It also helps reinforce having the same meter in all parts, and having the measure sequences fill the meter.

As the `measure` elements are also included in global, either solution, including a time element or including a duration attribute in the measure, are equivalent and have the same costs to scan.

> The current spec does not have a duration attribute attached to the measure element. I'm guessing you are proposing adding one, as a way of overriding the current meter set by the time element for one measure, or for supplying duration when there is no time element.

It was just a quick example of a possible solution without using tricks, such as hidden time signatures. But take it as a proposal for that, but only for that, not for overriding current meter. That is, if no `time` element is present then it is mandatory that `measure` elements include a 'duration' attribute, and vice-versa, the duration attribute in 'measure' elements is only valid when no `time` element is defined.

>  I'm against that because the time element seems to already cover those cases. It just needs to have no display aspect sometimes.

No, current draft spec. doesn't cover the "non time signature" case. In the current draft spec. (https://w3c.github.io/mnx/specification/#the-time-element) the `time`element requires a mandatory 'signature' attribute **that is always displayed**. Its value is a sum of ordered, undotted note value quantities defining the meter of a measure. To cover the 'no time signature' case probably a "0", "0/1" or "none" value should be included. And this value should render nothing (the no display aspect you mention). And it will be necessary to include the optional attribute 'measure' to provide the real measure duration.

IMO it is less verbose, simpler and clearer a solution such as the one I previously suggested, without having to relay on awkward special values (the "0/1" or "0" signature values) or on visual style values (hidden). But I will accept any other clear solution not relaying on hacks.

**Comment by clnoel** [comment]
@cecilios Okay. I think I'm going to alter that line in my list of requirements.

3. Has specified duration: The duration of the piece and each measure should be easily acqiured.

That lets us move on in this profile discussion to other topics. I'll be happy to debate with you in #69 how to not display a time signature while holding to that requirement.

------------
@joeberkovitz I think the individual constraint idea is a good one. That lets individual consumer programs gradually increase their capabilities, which is an important value from a programmer perspective.

**Comment by clnoel** [comment]
Here are the profile constraints I can see being important to my own consumer program (which, for example, can handle multi-metric but likes to know about it ahead of time!). Not all of these should go into the well-behaved/basic/standard profile.

`single-metric`: All parts have the same meter (if any) at any given point in the piece. Single-part pieces automatically meet this constraint. To me, measureless pieces also fall into this, as long as the total duration of each part is the same.

`multi-metric`: Each part can have a different meter, but the total duration of each part in whole notes must be the same.

`predetermined-length`: Each measure must have an easily calculable duration (in whole notes), so that the duration of the entire piece can be easily determined. Also, calculating the duration of any one part gets you the duration of every part, even if it's multi-metric or uses a different set of jumps.

`complete-measures`: Each measure exactly fills out its duration in every part. That is, there is at least one sequence in every measure, in every part, where the entire summed duration of all `<forward>` and `<event>` elements equals the duration of the measure. Also, no sequence can have a duration longer than the measure's duration.

`linear`: There are no locations where the order of the measures is not in sequence with the performance of the piece. (no repeats, 2nd endings, D.S., To Coda, etc.)

`consistent-jumps`: Every location where the order of the measures is not in sequence with the performance of the piece applies at the same time in the piece in all parts.  [Note: this would be violated by things like "rhythm figure" systems that one part will play repetitively for a section of the piece, but not by multi-metric pieces that have a repeat at a shared barline.]

`tablature`: Because not all programs that can handle notation can handle tablature, and it's my understanding that we are including TAB in MNX-Common. This might need to be a profile instead of a single constraint.

In addition, I can see non-constraining profile specifications. Where you indicate that you have included optional (non-semantic?) features that other programs might like to have, but can ignore without breaking.

`printable`: Contains layout information for printing to at least one paper size. (e.g. the `<print-layout>` element that we are considering in #57.)

`matches-performance`: Contains MNX-Generic style performance data to match the semantic layout. (See #95 and #67.)

I'm sure that there are more. Anyone else want to throw something into the pot?

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
