### ISSUE TITLE
Should fine horizontal adjustments be temporal, spatial or both?

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#7]
The fine positioning of directions, and many other appearance properties affecting horizontal position, could be specified in terms of a spatial distance from some anchor point (e.g. staff line fractions), or a metrical distance (e.g. beat fractions or ticks).

Is one of these models preferred? Are both models necessary? Can both kinds of positioning adjustments be employed at the same time?

At least some part of this issue relates to the question of how such adjustments are scaled when a measure is stretched or compressed as part of fitting into a justified page layout. Metrically based adjustments will presumably scale; spatial adjustments will probably not.

**Comment by siennamw** [comment]
In order to encode semantics, directions should be associated with `<event>` elements, or, when that is not possible, metrical distance should be used. Non-semantic positioning (purely visual adjustments that don't effect the meaning or timing of the direction) should be managed with CSS styles alone.

Metrical distance should be expressed in terms of beats, but the beat unit must be clearly defined somewhere to avoid ambiguity (in 6/8, is the beat on the 8th note or dotted quarter?).

Keywords like `start` and `end` could be used to indicate alignment with the start and end of a measure, respectively, assuming that `<measure>` is a containing element.

**Comment by Webern** [comment]
I believe that all "direction-like" things (dynamics, tempo markings, etc) should come with the option of attaching them directly to an event or attaching them to the measure instead.  In the case of a measure-attached direction, both the precise metrical (temporal) position in the measure should be specified along with the measure-relative X (spatial) position.  I think this is the only way to truly disambiguate the semantic and visual appearance of a direction.

**Comment by th-we** [comment]
I agree with @siennamw that the anchors should be defined in temporal terms and offsets should be left to CSS (using spacial units like interline spaces).

There is one thing that might be considered:  Sometimes, symbols like fermatas get anchored to a barline.  MEI solves this as follows:  Say we're in 4/4, then timestamps 1-4 mark the four beats, while 0 marks the leading barline and 5 the trailing one.

Using the MNX model, something could be anchored to the trailing barline in the same fashion, but that would probably have to be made part of the specs.  The question is whether it's also required that something can be anchored to leading barlines at a system start (when there are leading barlines, e.g. repeat barlines). If so, then this might be doable by anchoring to the first beat, using a special CSS offset value or unit to put it over the barline.

**Comment by joeberkovitz** [comment]
This issue has been resolved by the actions fixing #6. We now have both metrical and positional offsets that can apply to directions.

Event repositioning and alignment is going to be dealt with under #15.
